### ISSUE TITLE
Verify the search is working as expected 

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#10]
Specifically, an issue was found: search by “jdbc” can’t find https://clickhouse.com/docs/integrations/jdbc

**Comment by rfraposa** [comment]
Also, this “Loading…” can show for an unusually long amount of time:

![image](https://user-images.githubusercontent.com/5323324/161451669-4eedf191-65b4-4a6d-bc65-7aab62825243.png)

**Comment by DanRoscigno** [comment]
done
