### ISSUE TITLE
Add Sendinblue to adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#1006]
https://engineering.sendinblue.com/segmentation-to-target-the-right-audience/

A cluster of 100 servers (from the public Slack channel).

> Rohit Jain
  [1 minute ago](https://clickhousedb.slack.com/archives/CU170QE9H/p1680892231033689?thread_ts=1680885131.701149&cid=CU170QE9H)
thank you 
[@Alexey 'ClickHouse' Milovidov](https://clickhousedb.slack.com/team/U03K4MJJRK8)
 :slightly_smiling_face: yes I have 100 baremetal server today dedicated to ch cluster (50 shards 2 replica setup) and I have to use bigtable alongside to serve my transactional traffic
so was trying to understand if ytsaurus can combine both the use cases
I will contact them and tr it out for further queries offcourse :slightly_smiling_face:

**Comment by tylerhannan** [comment]
:) super cool

**Comment by tylerhannan** [comment]
closed in #1039
