### ISSUE TITLE
Need an explanation of the <secret> tag

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#101]
https://stackoverflow.com/questions/72197533/how-to-set-the-secret-tag-in-the-remote-servers-tag

**Comment by DanRoscigno** [comment]
Added:
A secret is created for the cluster named cluster_2S_1R with the value mysecretphrase. The secret is shared across all of the remote servers in the environment to ensure that the correct servers are joined together.
