### ISSUE TITLE
Integrate with documentation browsers

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#102]
Specifically:
- [ ] DevDocs https://devdocs.io/ 
- [ ] Dash https://kapeli.com/dash

**Comment by rfraposa** [comment]
Kapeli replied to my email with a link to this page: https://kapeli.com/docsets

**Comment by rfraposa** [comment]
Just found this for creating an offline version of the docs - looks much easier than DevDocs or Dash: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-pwa

**Comment by justindeguzman** [comment]
Closed as not high priority, this will be very difficult to maintain
