### ISSUE TITLE
Add TablePlus to integrations page.

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#1031]
One of our students in the ClickHouse Workshop today said that they use TablePlus with ClickHouse as the database backend.

I was unable to find it in the TablePlus documentation, but did find a few references to it:

* [Feature request: ClickHouse support](https://github.com/TablePlus/TablePlus/issues/670#top) #670 - looks like it requires either the ClickHouse MySQL Interface or the PostgreSQL Interface
* https://tableplus.com/blog/2018/09/changelogs-windows.html 
* * TablePlus 4.9.6 - Build 192 - Improved ClickHouse Driver.
* * TablePlus 4.9.9 - Build 196 - [ClickHouse] Support SSL.

Name: TablePlus
Logo: https://tableplus.com/resources/favicons/apple-icon-120x120.png
Category: Data Management
Description: Modern, native, and friendly GUI tool for relational databases: MySQL, PostgreSQL, SQLite & more
Website: https://tableplus.com/

**Comment by johnnymatthews** [comment]
It looks like ClickHouse is still not supported (at least according to their docs):

![Image](https://github.com/ClickHouse/clickhouse-docs/assets/9611008/fc67f8cf-e8d5-4341-84f5-cb3be0d4e324)

In the interest of keeping this repo tidy, I'm gonna close this issue.
