### ISSUE TITLE
Explain how to connect to ClickHouse Cloud in JDBC integration page.

### ISSUE THREAD

**Issue by tom-clickhouse** [ClickHouse/clickhouse-docs#104]
The JDBC url requires a special port and ssl parameter in order to connect to ClickHouse cloud. 
And in slack channel for private preview customer the customer specifically asked for help because it is not so obvious how to connect to our cloud.

Therefore let's add a special cloud section to the [Connecting Applications to ClickHouse with JDBC doc](https://clickhouse.com/docs/en/integrations/jdbc/jdbc-with-clickhouse-2).

- use screenshots from the control plane with the https connection values
- give concrete java example program, e.g. 
```
import com.clickhouse.jdbc.ClickHouseDataSource;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

// connect to cloud instance
public class JDBC2CHCloud {
    public static void main(String[] args) throws Exception {

        String url = "jdbc:ch://yxaeq2tmh3.eu-west-1.aws.clickhouse.cloud:8443/default?ssl=true";

        ClickHouseDataSource dataSource = new ClickHouseDataSource(url);
        try (Connection connection = dataSource.getConnection("username", "pw");
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(" select * from system.tables limit 10")) {
            ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
            int columns = resultSetMetaData.getColumnCount();
            while (resultSet.next()) {
                for (int c = 1; c <= columns; c++) {
                    System.out.print(resultSetMetaData.getColumnName(c) + ":" + resultSet.getString(c) + (c < columns ? ", " : "\n"));
                }
            }
        }
    }
}
```

**Comment by DanRoscigno** [comment]
closed by #104

**Comment by DanRoscigno** [comment]
@CamiloSierraH you can use this URL https://clickhouse.cloud/integrations/java I will ask the integrations team to sync the docs from the cloud UI to the documentation. @ClickHouse/integrations

**Comment by DanRoscigno** [comment]
@mshustov I don't know how to assign this to the team, is it supposed to happen if the label is added?

**Comment by DanRoscigno** [comment]
@CamiloSierraH , if this was added, would it be sufficient?:
```java
    Properties prop = new Properties();
    prop.setProperty("username", "default");
    prop.setProperty("password", "<password>");
    Connection conn = DriverManager.getConnection("jdbc:ch:https://<host>:8443?insert_quorum=auto", prop);
```

**Comment by mshustov** [comment]
@DanRoscigno in this case it's better to assign an owner - @mzitnik

**Comment by gingerwizard** [comment]
I think this is closed @mzitnik 

![image](https://github.com/user-attachments/assets/5fa32cca-0d7d-4fb9-8f25-e09667f051bf)


The example is missing `ssl=true`, should we add cc @mshustov
