### ISSUE TITLE
Investigate and fix `JOIN` query in `SELECT` and `JOIN` reference pages.

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/clickhouse-docs#1059]
Not sure which one (none?) is correct.

[SELECT Query](https://clickhouse.com/docs/en/sql-reference/statements/select):

```
[GLOBAL] [ANY|ALL|ASOF] [INNER|LEFT|RIGHT|FULL|CROSS] [OUTER|SEMI|ANTI] JOIN (subquery)|table (ON <expr_list>)|(USING <column_list>)
```

[JOIN Clause](https://clickhouse.com/docs/en/sql-reference/statements/select/join):

```
[GLOBAL] [INNER|LEFT|RIGHT|FULL|CROSS] [OUTER|SEMI|ANTI|ANY|ASOF] JOIN <right_table>
(ON <expr_list>)|(USING <column_list>) ...
```

- `ANY`, `ASOF` moved to 3rd section
- `ALL` missing
- testing shows both syntaxes accepted...

**Comment by johnnymatthews** [comment]
Both versions work for me too. I just quickly tested the `ALL` qualifier with `JOIN` and it worked fine. I'll add it into the docs.
