### ISSUE TITLE
PR workflow fails on PRs based on personal forks (vs. branches in this repo)

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/clickhouse-docs#107]
I am not a GitHub expert, but this looks to me like the workflow failed because my PR was based on a fork and not a local branch:
```
++ git branch --show-current
+ GIT_BRANCH=main
+ '[' reorder-example-datasets ']'
+ '[' reorder-example-datasets == main ']'
+ git fetch origin --depth=1 -- reorder-example-datasets:reorder-example-datasets
fatal: couldn't find remote ref reorder-example-datasets
```
I replaced the PR with another based on a branch created in this repo and it worked fine.

**Comment by rfraposa** [comment]
Yes - this is an issue! Do we know how to fix it?

**Comment by DanRoscigno** [comment]
no, but I will look into it.  I put it there to remind myself.  When I want to build a preview of other people's code I use the command `gh pr checkout <pr number>` as it works without me having to add a remote for their repo.  That might be the answer?  I have never worked with git workflows.

**Comment by DanRoscigno** [comment]
done
