### ISSUE TITLE
dbt-clickhouse integration documentation incorrectly states ephemeral models are not supported

### ISSUE THREAD

**Issue by damirbk** [ClickHouse/clickhouse-docs#1072]
The [Integrating with dbt](https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/data-ingestion/etl-tools/dbt/index.md) page states that ephemeral models are not supported in dbt-clickhouse (twice, once under Concepts and once under Limitations). However, [this closed issue](https://github.com/ClickHouse/dbt-clickhouse/issues/126) makes it clear that they are indeed supported.

**Comment by DanRoscigno** [comment]
@genzgd can you please have a look?  In https://github.com/ClickHouse/dbt-clickhouse/issues/126 you mentioned updating the docs, but they still say that ephemeral models are not supported.

**Comment by genzgd** [comment]
This was fixed by the reporter with https://github.com/ClickHouse/clickhouse-docs/pull/1076.  That particular integrations page needs some additional work but ephemeral model and http support at least are correct now.

**Comment by DanRoscigno** [comment]
Thanks so much @damirbk and @genzgd !
