### ISSUE TITLE
Add wspr.live to adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#1086]
https://wspr.live/

Attached directly to ClickHouse. (So, the reference is the website itself)
Or https://twitter.com/HB9VQQ/status/1652723207475015680

![Screenshot_20230430_193610](https://user-images.githubusercontent.com/18581488/235367736-64f2cd2e-c1c0-434c-9c8a-7a2c8287c9c8.png)

**Comment by tylerhannan** [comment]
Closed with #1122
