### ISSUE TITLE
Secure ClickHouse Keeper

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#1091]
Add a KB article on how to secure ClickHouse Keeper. (Is this a common task?)

**Comment by e-mars** [comment]
@rfraposa , i have some examples with securing for SSL and also using like `<identity>ch_keeper_user:password</identity>` configuration.
however, it is not a common ask so not sure how high on priority list this is for a user guide and/or KB.

**Comment by DanRoscigno** [comment]
closed by #1251
