### ISSUE TITLE
Add Ookla to adopters

### ISSUE THREAD

**Issue by tylerhannan** [ClickHouse/clickhouse-docs#1120]

**Comment by tylerhannan** [comment]
pausing until after JonTheBeach to reference the presentation being given. https://www.jonthebeach.com/speakers/110/Sammy+Landstrom

**Comment by alexey-milovidov** [comment]
@tylerhannan, the conference has already happened, let's continue.

**Comment by tylerhannan** [comment]
Added in #1272
