### ISSUE TITLE
Cannot find documentation for executable UDFs

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#1147]
Only executable table functions are documented, not normal functions.

**Comment by DanRoscigno** [comment]
Is this what you are looking for? https://clickhouse.com/docs/en/sql-reference/statements/create/function

**Comment by alexey-milovidov** [comment]
Not so easy to find. I have to find this page, and then scroll down, and follow the link to executable UDFs,
being not confused with executable UDTFs.

**Comment by DanRoscigno** [comment]
Once I reindex search tonight it should be findable at https://clickhouse.com/docs/en/sql-reference/functions/udf

**Comment by DanRoscigno** [comment]
I think we can close this; a search for UDF or User defined gets the reader to https://clickhouse.com/docs/en/sql-reference/functions/udf
