### ISSUE TITLE
Update DBeaver page

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/clickhouse-docs#1181]
The DBeaver page is a bit outdated. It's better to update the content once DBeaver 23.1.0 is out.

1. Update instructions and screenshots for SSL connection, because DBeaver now has separate tab for SSL settings
2. Update connection creation screenshot and provide one example to connecting to multiple endpoints, as DBeaver supports custom URL - dbeaver/dbeaver#16545
3. Better to emphasize to use 23.1.0 or above due to dbeaver/dbeaver#20014

**Comment by DanRoscigno** [comment]
DBeaver 23.1 was released yesterday, so I will add this now.
