### ISSUE TITLE
Add breadcrumbs to top navigation

### ISSUE THREAD

**Issue by Slach** [ClickHouse/clickhouse-docs#1186]
For example open 
https://clickhouse.com/docs/en/operations/system-tables/zookeeper
and try to understand where is your article, which part of documentation you actually view?
![image](https://github.com/ClickHouse/clickhouse-docs/assets/105560/088b9169-be83-446c-aa7e-70adaf2cb94e)
You need to scroll down to see wher is current document 
![image](https://github.com/ClickHouse/clickhouse-docs/assets/105560/ceb0b137-a627-4e2c-828a-9d4e26d0b519)

**Comment by rfraposa** [comment]
@gjones @justindeguzman - breadcrumbs were removed during the redesign. Thoughts?

**Comment by gjones** [comment]
Interesting, looking at the latest designs, the breadcrumbs were not supposed to be removed so I think its just an oversight on our part. We'll create an issue to get them re-added.

**Comment by justindeguzman** [comment]
@rfraposa I remember discussing this and with the new docs re-org in the sidebar, it was more complicated to add breadcrumbs. We'll need to have some eng cycles for this, it likely won't be a very simple change @gjones

**Comment by rfraposa** [comment]
It's just a setting in Docusaurus. Here is what they would look like:

<img width="1133" alt="Screenshot 2023-05-30 at 9 58 56 AM" src="https://github.com/ClickHouse/clickhouse-docs/assets/5323324/7acee208-f3e9-45d1-910d-9a08c958b0af">

**Comment by gjones** [comment]
I think @justindeguzman's concerns were more about ensuring that the breadcrumbs match up with the information architecture established in the left navigation. That correct Justin? How do you feel about turning on the above?

**Comment by justindeguzman** [comment]
Yes that was my concern @gjones. @rfraposa let's deploy to a branch for now and if it's not too out-of-sync, we can deploy to prod? If the breadcrumbs don't match up with the navigation, that may end up being more confusing to users.

**Comment by rfraposa** [comment]
The breadcrumbs themselves seem fine in terms of the navigation and letting the user know where they are. There is only one "odd" behavior that I notice: there are quite a few breadcrumbs that don't link to pages. 

For  example, on the following breadcrumbs you can click on **CREATE**, but **Statements** and **Introduction** are not pages - so they are not clickable:

<img width="401" alt="Screenshot 2023-06-01 at 3 30 50 AM" src="https://github.com/ClickHouse/clickhouse-docs/assets/5323324/a03bdc5b-38e6-4709-8503-32a3bab1ba6c">

**Comment by justindeguzman** [comment]
Ok this looks good! Thanks @rfraposa
