### ISSUE TITLE
Setup instructions for GCP Private Service Connect (PSC)

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#1213]
Here are the instructions for ClickHouse Cloud for setting up a Private Service Connect ("PSC") secure private link. Please note, PSC is only available when using GCP as your ClickHouse Cloud backend provider and on Production-tier services (not available for Development-tier services):

**Create PSC Endpoint**
1. Navigate to Network services -> Private Service Connect
2. Open Private Service Connect creation dialog by clicking on the “Connect Endpoint” button.

**Target:** please use Published service
**Target service:** projects/dataplane-production/regions/us-central1/serviceAttachments/production-us-central1-clickhouse-cloud
**Endpoint name:** please set name for PSC Endpoint.
**Network/Subnetwork/IP address:** please choose the network you want to use for connection. You will need to create an IP address or use an existing one for the Private Service Connect endpoint.
To make the endpoint available from any region, you can enable the "Enable global access" checkbox.

**Example of created PSC Endpoint:**
![endpoint-example](https://github.com/ClickHouse/clickhouse-docs/assets/8918693/bbb340e6-98d8-4f9a-b570-0022d66fb810)

3. Please copy PSC Connection ID & IP address (10.142.0.2 in this example), you will need this information in next steps.

**Create Private DNS zone**
1. Please open Network services -> Cloud DNS
2. Click “Create Zone” button:
![create-zone](https://github.com/ClickHouse/clickhouse-docs/assets/8918693/42d58f38-2644-409e-ac11-f2803470a955)

**Zone type:** “Private”
**Zone name:** please set zone name.
**DNS name:** us-central1.p.gcp.clickhouse.cloud
**Networks:** please attach a DNS zone to networks you are planning to use for connecting to ClickHouse Cloud via PSC

**Create a wildcard record**
1. Go to Network services->Cloud DNS
2. Open zone created in previous step (us-central1.p.gcp.clickhouse.cloud)
3. Create wildcard (*) record and point it to IP from "Create PSC Endpoint" step:
![wildcard-record](https://github.com/ClickHouse/clickhouse-docs/assets/8918693/dddb3f9f-8328-4e50-8c5b-15b60f85ee95)

**Provide information to ClickHouse via Support Case**
1. PSC Connection ID(s) from "Create PSC Endpoint" step
2. GCP projectID(s)
3. ClickHouse instance ID(s) that should be available via Private Service Connect.

**How it works**
**instance hostname example:** abcd.us-central1.gcp.clickhouse.cloud
**to connect via PSC, use:** abcd.us-central1.p.gcp.clickhouse.cloud host
**to connect via internet, use:** abcd.us-central1.gcp.clickhouse.cloud host

**Comment by bianpengyuan** [comment]
Google doc for this: https://docs.google.com/document/d/1_6HhCJvqV9XzREp6U284pPWRADNz0WIcTYd_8TTtXSI/edit?usp=sharing
