### ISSUE TITLE
Add SQL reference documentation for Transactions

### ISSUE THREAD

**Issue by e-mars** [ClickHouse/clickhouse-docs#122]
Experimental Feature, transaction support:
https://clickhouse.com/docs/en/whats-new/changelog/#:~:text=Added%20support%20for%20transactions%20for%20simple%20MergeTree%20tables.%20This%20feature%20is%20highly%20experimental%20and%20not%20recommended%20for%20production.%20Part%20of%20%2322086.%20%2324258%20(tavplubix).

**Comment by DanRoscigno** [comment]
This is not ready to be documented.  Too early.
