### ISSUE TITLE
Find missing pages.

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#1229]
Updated list:

- [x] https://clickhouse.com/docs/en/cloud/manage/postman
- [ ] https://clickhouse.com/docs/en/faq/billing
- [ ] https://clickhouse.com/docs/en/faq/general
- [ ] https://clickhouse.com/docs/en/faq/general/columnar-database
- [ ] https://clickhouse.com/docs/en/faq/general/dbms-naming
- [ ] https://clickhouse.com/docs/en/faq/general/how-do-i-contribute-code-to-clickhouse
- [ ] https://clickhouse.com/docs/en/faq/general/mapreduce
- [ ] https://clickhouse.com/docs/en/faq/general/ne-tormozit
- [ ] https://clickhouse.com/docs/en/faq/general/olap
- [ ] https://clickhouse.com/docs/en/faq/general/who-is-using-clickhouse
- [ ] https://clickhouse.com/docs/en/faq/general/why-clickhouse-is-so-fast
- [ ] https://clickhouse.com/docs/en/faq/integration
- [ ] https://clickhouse.com/docs/en/faq/integration/json-import
- [ ] https://clickhouse.com/docs/en/faq/integration/oracle-odbc
- [ ] https://clickhouse.com/docs/en/faq/marketplace
- [ ] https://clickhouse.com/docs/en/faq/operations
- [ ] https://clickhouse.com/docs/en/faq/operations/delete-old-data
- [ ] https://clickhouse.com/docs/en/faq/operations/deploy-separate-storage-and-compute
- [ ] https://clickhouse.com/docs/en/faq/operations/multi-region-replication
- [ ] https://clickhouse.com/docs/en/faq/operations/production
- [ ] https://clickhouse.com/docs/en/faq/troubleshooting
- [ ] https://clickhouse.com/docs/en/faq/use-cases
- [ ] https://clickhouse.com/docs/en/faq/use-cases/key-value
- [ ] https://clickhouse.com/docs/en/faq/use-cases/time-series
- [x] https://clickhouse.com/docs/en/integrations/data-ingestion/kafka/code
- [x] https://clickhouse.com/docs/en/integrations/data-ingestion/kafka/code/connectors
- [x] https://clickhouse.com/docs/en/integrations/data-ingestion/kafka/code/producer
- [x] https://clickhouse.com/docs/en/integrations/data-ingestion/upload-file-to-clickhouse-cloud
- [x] https://clickhouse.com/docs/en/quick-start

<details>
  <summary>code to generate</summary>

`missingNav.go`
```go
package main

import (
	"fmt"

	"github.com/gocolly/colly/v2"
)

func main() {
	// Array containing all the known URLs in a sitemap
	knownUrls := []string{}
	navIsFound := false

	// Create a Collector limited to clickhouse.com
	c := colly.NewCollector(colly.AllowedDomains("clickhouse.com"))

	// we are parsing the XML file `sitemap.xml`, so add
	// an OnXML callback to add each URL to the `knownUrls array
	c.OnXML("//urlset/url/loc", func(e *colly.XMLElement) {
		knownUrls = append(knownUrls, e.Text)
	})

        // the OnHTML callback gets called when processing an HTML
	// file, which happens in the for loop processing all entries
	// in `knownUrls`.  We want this to check for the left side nav
	// and print a message if the nav is missing.  The first entry
	// in the nav is the search bar, it has two IDs, one for Docs
	// and one for the knowledgebase, so two call backs.
	c.OnHTML(".sidebarSearchContainer_Lwc8", func(e *colly.HTMLElement) {
		if e.Text == "Search" {
			navIsFound = true
		}
        })

	// another OnHTML callback for KB articles 
	c.OnHTML(".sidebarSearchContainer_BOHF", func(e *colly.HTMLElement) {
		if e.Text == "Search" {
			navIsFound = true
		}
        })

	// Start the collector to grab the sitempa and populate
	// the `knownUrls` array
	c.Visit("https://clickhouse.com/docs/sitemap.xml")

	// for loop processing the `knownUrls`.  The `c.Visit(url)`
	// will process an HTML file and cause the `OnHTML` callback
	// to process the page
	for _, url := range knownUrls {
		// reset navIsFound to false on each iteration
		navIsFound = false
		c.Visit(url)
		// navIsFound gets set to `true` in the OnHTML
		// callbacks if the nav is present in the pages
		// if it is still `false` at this point, then
		// the nav is missing.
		if navIsFound == false {
			fmt.Println("- [ ]", url)
		}
	}
}
```

go.mod
```go
module localhost/missingNav

go 1.20

require (
	github.com/PuerkitoBio/goquery v1.5.1 // indirect
	github.com/andybalholm/cascadia v1.2.0 // indirect
	github.com/antchfx/htmlquery v1.2.3 // indirect
	github.com/antchfx/xmlquery v1.2.4 // indirect
	github.com/antchfx/xpath v1.1.8 // indirect
	github.com/gobwas/glob v0.2.3 // indirect
	github.com/gocolly/colly/v2 v2.1.0 // indirect
	github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e // indirect
	github.com/golang/protobuf v1.4.2 // indirect
	github.com/kennygrant/sanitize v1.2.4 // indirect
	github.com/saintfish/chardet v0.0.0-20120816061221-3af4cd4741ca // indirect
	github.com/temoto/robotstxt v1.1.1 // indirect
	golang.org/x/net v0.0.0-20200602114024-627f9648deb9 // indirect
	golang.org/x/text v0.3.2 // indirect
	google.golang.org/appengine v1.6.6 // indirect
	google.golang.org/protobuf v1.24.0 // indirect
)
```
</details>

**Comment by rfraposa** [comment]
- [ ] https://clickhouse.com/docs/en/faq/operations/production

**Comment by DanRoscigno** [comment]
closing

**Comment by johnnymatthews** [comment]
`/docs/en/quick-start` is duplicated on https://clickhouse.com/docs/en/cloud-quick-start. Gonna delete `/docs/en/quick-start`

**Comment by rfraposa** [comment]
And add a redirect to avoid a 404...

**Comment by johnnymatthews** [comment]
> 8 years of docs + 3 major redesigns in the past 2 years = a lot of redirects 😄

Makes sense 😅 ! One major issue I've noticed is that we've got redirects that push users to _another_ redirect. We could certainly trim the fat in a lot of places, and add wildcard redirects for super old/unused links. But anyway, that's another issue entirely.
