### ISSUE TITLE
Docs versioning request for feature introduction

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#123]
In Twitter, we received the following enhancement request:

suggestion: indicate in the docs in which versions things became available. For example:  doesn't say when `date_diff` became available. groupArraySorted also showed up without a version indication even though it was only in master (was since reverted entirely)

https://twitter.com/roncohen/status/1526572164723392512

**Comment by tbragin** [comment]
I think @rfraposa  made a good point in Slack about why this should be a low priority request. Copying verbatim. 

> Rich Raposa  [7:25 AM]
> If we are truly a Cloud company (not just Cloud-first), then versions should not be a major concern for the end-user.  I’m much more interested in how we deliver cloud vs. on-prem docs.  It would be awesome to know when a feature was made available, but if it’s that important to you, then I would argue that with a little bit of searching in the Changelogs you could figure it out.
> Rich Raposa  [7:26 AM]
> If you are using the Cloud, and therefore using the latest version of ClickHouse, then every feature should be available to you…so the versioning becomes a minor concern
