### ISSUE TITLE
Fix inbound 404ing links from Cloudflare blog.

### ISSUE THREAD

**Issue by SwetaIIFL** [ClickHouse/clickhouse-docs#1247]
https://clickhouse.com/docs/en/single#replicatedaggregatingmergetree and https://clickhouse.com/docs/en/single#create-view return 
"page not found"error

These pages are referred from https://blog.cloudflare.com/http-analytics-for-6m-requests-per-second-using-clickhouse/

**Comment by justindeguzman** [comment]
Thank you @SwetaIIFL. Here is the full list of broken links, from @chhetripradeep

https://pastila.nl/?08e7649e/bbb0ab8b6bbe2ace5ec8ca94dd47161a
