### ISSUE TITLE
Update ClickHouse Cloud API to reflect working Terraform provider

### ISSUE THREAD

**Issue by arisarose** [ClickHouse/clickhouse-docs#1263]
https://clickhouse.com/docs/en/cloud/manage/api/api-overview needs to be updated to reflect the, now available, Terraform provider.  Specifically, this statement is no longer relevant: "Our Terraform API is coming soon, and we're looking for beta testers. If you're interested in trying out our Terraform API to programmatically provision services, please contact ClickHouse Support at https://clickhouse.cloud/support". cc: @krithika-ch

**Comment by DanRoscigno** [comment]
done https://clickhouse.com/docs/en/cloud/manage/api/api-overview
