### ISSUE TITLE
Missing docs for Meilisearch

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#1274]
We have a `meilisearch` table function and `Meilisearch` table engine, and neither appear in the documentation

**Comment by rfraposa** [comment]
https://github.com/ClickHouse/ClickHouse/commit/96cfc7f07adbeb78500be496165ae3b724e413af

**Comment by DanRoscigno** [comment]
The Meilisearch integration does not work; leave it out of docs until it works.
