### ISSUE TITLE
Missing functions on "List of Aggregate Functions" page

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#1275]
This page is not auto-generated, so new functions have to be manually added to it: https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference

I noticed some newer agg functions like quantile(s)GK and kolmogorovSmirnovTest are missing.

**Comment by DanRoscigno** [comment]
corr.md
deltasum.md
deltasumtimestamp.md
entropy.md
exponentialmovingaverage.md
grouparraysample.md
intervalLengthSum.md
kolmogorovsmirnovtest.md
mannwhitneyutest.md
meanztest.md
median.md
quantileGK.md
quantileinterpolatedweighted.md
rankCorr.md
sparkbar.md
studentttest.md
sumcount.md
sumkahan.md
welchttest.md
