### ISSUE TITLE
increase snippet returned by Algolia docsearch

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/clickhouse-docs#1289]
URL we are testing with:
https://clickhouse.com/docs/search?q=uncompressed_hash_of_compressed_files

Current state:
![image](https://github.com/ClickHouse/clickhouse-docs/assets/25182304/33464fb3-ecb7-415d-9132-ff61986efa79)

**Comment by justindeguzman** [comment]
Closing as we will be redesigning docs search soon
