### ISSUE TITLE
Window functions are not explained in detail

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#130]
Each window function should have its own page in the docs:  https://clickhouse.com/docs/en/sql-reference/window-functions/

**Comment by qoega** [comment]
more https://github.com/ClickHouse/ClickHouse/pull/37848 :)

**Comment by DanRoscigno** [comment]
https://clickhouse.com/blog/working-with-time-series-data-and-functions-ClickHouse

**Comment by rfraposa** [comment]
Alexey added lots of examples since this issue was created. I think we're good
