### ISSUE TITLE
Add a note about Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [ClickHouse/clickhouse-docs#1392]
Hi!

In https://github.com/ClickHouse/ClickHouse/issues/44567#issuecomment-1589541199 I did some benchmarks for ClickHouse with Profile-Guided Optimization (PGO) and got good results. @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/issues/44567#issuecomment-1590164425 suggested adding a note about this somewhere to the documentation.

I suggest adding PGO note somewhere in performance-oriented section of the ClickHouse documentation.

**Comment by alexey-milovidov** [comment]
Yes, let's add it. Just copy-paste it in some appropriate place in the docs.

**Comment by zamazan4ik** [comment]
Now we have PGO-related documentation here: https://clickhouse.com/docs/en/operations/optimizing-performance/profile-guided-optimization

I think the issue can be closed as completed.
