### ISSUE TITLE
A new documentation page does not appear in the sidebar

### ISSUE THREAD

**Issue by zamazan4ik** [ClickHouse/clickhouse-docs#1411]
A new documentation page was introduced in https://github.com/ClickHouse/ClickHouse/pull/52877 . But according to the https://github.com/ClickHouse/ClickHouse/pull/52877#issuecomment-1661270338 it doesn't work as expected. One of the ideas is trying to fix this by adding missing symlinks to the page (it's done at https://github.com/ClickHouse/ClickHouse/pull/52939).

A person in Russian-speaking Telegram chat about ClickHouse [suggested](https://t.me/clickhouse_ru/335651) creating an issue about the case here.

**Comment by den-crane** [comment]
no sidebar: https://clickhouse.com/docs/en/operations/optimizing-performance/profile-guided-optimization

**Comment by zamazan4ik** [comment]
https://github.com/ClickHouse/ClickHouse/pull/52939 didn't help. So now I have no idea what is going on wrong here and need help from the ClickHouse Docs maintainers.

**Comment by justindeguzman** [comment]
This is fixed in this [PR](https://github.com/ClickHouse/clickhouse-docs/pull/1427). New pages must be specified in `sidebars.js`.

<img width="291" alt="Screenshot 2023-08-11 at 3 15 32 AM" src="https://github.com/ClickHouse/clickhouse-docs/assets/3936029/41a4aa08-e566-4f78-9b8d-d60e731b8610">
