### ISSUE TITLE
Document all available settings.

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/clickhouse-docs#142]
name
definition
scope
cloud, os, both
basics
deeper

**Comment by thomoco** [comment]
thanks for filing @DanRoscigno - this is the list of info that would be very quick and helpful to users, as @genzgd and I discussed:

* system.settings - does this need to be single top-level Doc
    * definition
    * scope (global/db/table)
    * availability: open-source, Cloud, both, deprecated
    * configuration
    * link to more information

**Comment by mshustov** [comment]
@slvrtrn wrote a script to capture settings from the ClickHouse repository to create TypeScript definitions. Feel free to ping Serge if the script can be helpful for this use case.

**Comment by rschu1ze** [comment]
Will be done in the scope of #2730, marking as duplicate.
