### ISSUE TITLE
Add documentation of our limit for concurrent queries per replica in Cloud

### ISSUE THREAD

**Issue by kellytoole** [ClickHouse/clickhouse-docs#1430]
See Slack thread here: https://clickhouse-inc.slack.com/archives/C03A9B0H05T/p1691768874380409

**Comment by kellytoole** [comment]
@justindeguzman: when this update is made, we'll link to it in our Snowflake comparison blog as well. cc @gingerwizard

**Comment by justindeguzman** [comment]
Merged in this PR: https://github.com/ClickHouse/clickhouse-docs/pull/1502
