### ISSUE TITLE
Extension of functionality of format_avro_schema_registry_url parameter

### ISSUE THREAD

**Issue by GorodnovNikolas** [ClickHouse/clickhouse-docs#1443]
Dear developers!
I have the following problem with ClickHouse
I tried to create a connection to Kafka to read Avro, I have Kafka itself and Apicurio Schema Registry.

CREATE TABLE IF NOT EXISTS test.kafka_con (
data String
) ENGINE = Kafka
SETTINGS kafka_broker_list = 'broker1:9092, broker2:9092, broker3:9092',
kafka_topic_list = 'topic.name',
kafka_group_name = 'myGroup',
kafka_format = 'AvroConfluent',
format_avro_schema_registry_url = 'http://schema-registry.my-proj.com/apis/ccompat/v6'

CREATE MATERIALIZED VIEW test.kafka_view ENGINE = Memory AS
SELECT
*
FROM test.kafka_con

I was getting an error informing me that the schema was not valid:
DB::HTTPException: Received error from remote server /schemas/ids/333. HTTP status code: 404 Not Found,
body: { "message": "RESTEASY003210: Could not find resource for full path: http://schema-registry.my-proj.com/schemas/ids/333",
"error_code":404, "detail": "NotFoundException: RESTEASY003210: Could not find resource for full path http://schema-registry.my-proj.com/schemas/ids/333".

The point is that the Apicurio Schema Registry URL that I specify (http://schema-registry.my-proj.com/apis/ccompat/v6) is changed during schema validation inside the ClickHouse code to (http://schema-registry.my-proj.com/schemas/ids/333), while the schema number(333) that is assigned to the topic(topic.name) is found to be correct

The problem is that in the ClickHouse code in the AvroRowInputFormat class in the AvroConfluentRowInputFormat::SchemaRegistry code block, there is an input parameter base_url, a given string value, namely "/schemas/ids/" and a schema id. The string looks like this: poco::URI url(base_url, "/schemas/ids/" + std::to_string(id));
During validation, the part of my URL that I specify in the format_avro_schema_registry_url parameter is trimmed and in place of the trimmed part, a constant value "/schemas/ids/" is substituted and nothing is found on the generated Clickhouse URL, as such path does not exist.
So, instead of http://schema-registry.my-proj.com/apis/ccompat/v6/schemas/ids/333 , you get http://schema-registry.my-proj.com/schemas/ids/333.

The solution would be: instead of "/schemas/ids/", make an input parameter that could be specified together with format_avro_schema_registry_url if necessary, in order to have a more flexible model of URL passing for Confluent Schema Registry, and by default, this parameter should remain "/schemas/ids/", so that its specification would remain optional.

**Comment by johnnymatthews** [comment]
This issue would be better suited in the [main ClickHouse repository](https://github.com/clickhouse/clickhouse). I'm going to close this issue. if you're still having problems please raise an issue in github.com/clickhouse/clickhouse.
