### ISSUE TITLE
More examples and tutorials with ClickHouse and Grafana

### ISSUE THREAD

**Issue by justindeguzman** [ClickHouse/clickhouse-docs#1445]
Create tutorials/dashboards for different use cases like observability, web analytics, etc.

**Comment by johnnymatthews** [comment]
This issue is _super_ general, and is partially addressed by the new docs homepage: 

![image](https://github.com/ClickHouse/clickhouse-docs/assets/9611008/2f82fe3b-b8a4-401c-8b1d-36a7c3056aa3)

I'm gonna close this one.
