### ISSUE TITLE
Slug for lightweight-update & delete have a typo

### ISSUE THREAD

**Issue by tobiaslins** [ClickHouse/clickhouse-docs#1469]
I wanted to share a docs link for lightweight updates and saw that there are typos in there.
`slug: /en/guides/developer/lightweght-update` is missing the `i`
https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/guides/developer/lightweight-update.md?plain=1#L2
https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/guides/developer/lightweight-delete.md?plain=1#L2

**Comment by justindeguzman** [comment]
Good catch @tobiaslins! This is fixed here: https://github.com/ClickHouse/clickhouse-docs/pull/1478
