### ISSUE TITLE
Add Splio to adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#1500]
François BONICEL (Splio)
https://clickhousedb.slack.com/archives/C04N3AU38DV/p1693995069023669
> :wave: Hello All, I'm Global VP Engineering at Splio, a Marketing Software Company, and we use Clickhouse in Prod for 2 years for Analytics, Segmentation and Monitoring Use Cases.

**Comment by tylerhannan** [comment]
Added in #1515
