### ISSUE TITLE
Add Doctor Droid to adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#1508]
https://clickhousedb.slack.com/archives/C04N3AU38DV/p1694151014185729

> Dipesh Mittal

> Hi Everyone. I am Dipesh, Founder & CTO @ Dr Droid. We use clickhouse extensively and I am excited to learn from the community here.

**Comment by tylerhannan** [comment]
Added in #1515

**Comment by tylerhannan** [comment]
Added in #1515
