### ISSUE TITLE
Add Gigasheet to Integrations

### ISSUE THREAD

**Issue by tylerhannan** [ClickHouse/clickhouse-docs#1529]
I noticed you have some partner integrations [here](https://clickhouse.com/docs/en/integrations) and I wanted to find out who I might talk to at ClickHouse about getting listed? We have an offering where we run Gigasheet as big data spreadsheet "viewer" on customers' ClickHouse data. Would love to be listed here :slightly_smiling_face:

**Comment by n1njash03s** [comment]
![image](https://github.com/ClickHouse/clickhouse-docs/assets/10323663/f738f665-0db1-4a7f-82ef-936d76919842)

**Comment by n1njash03s** [comment]
We've published a dedicated landing page for our Clickhouse integration https://gigasheet.com/enterprise-clickhouse
