### ISSUE TITLE
Atlas support

### ISSUE THREAD

**Issue by gempir** [ClickHouse/clickhouse-docs#1582]
https://github.com/ClickHouse/clickhouse-docs/commit/989ff0235bbd1a486b79e97a7e21ea6fda9b216b

This commit added a few tools to manage clickhouse schemas, it claims Atlas supports Clickhouse.

But I can't find a single other reference of that being the case and there is an outstanding issue asking for Clickhouse support on the Atlas repo, so i'd say it's not likely that is is currently supported.

Or did someone do their own tests and it somehow works?

https://github.com/ariga/atlas/issues/1456

**Comment by bx2** [comment]
No, I did try it and it does not work. It should be removed from the docs as it is misleading.

**Comment by johnnymatthews** [comment]
Thanks for the flag! I'm removed Atlas from that listing.

**Comment by a8m** [comment]
Hey! Just fyi, we added Clickhouse as an official driver of Atlas a month ago: https://atlasgo.io/blog/2023/12/19/atlas-v-0-16

**Comment by johnnymatthews** [comment]
Ok nice, thanks for the update @a8m.
