### ISSUE TITLE
Add tags to Knowledge Base articles.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1611]
The knowledge base is great, but it's pretty hard to filter through. Algolia does an _ok_ job of finding the stuff you're looking for, but we can improve the results by adding tags to each article.

An easy, but potentially problematic, way to do this is to have GPT suggest tags. If we go this route we should make sure to validate every tag to ensure it actually makes sense.

Or we can manually throw tags into articles based on what we (the docs team) think they should be.

**Comment by gingerwizard** [comment]
Closing in favor of https://github.com/ClickHouse/clickhouse-docs/issues/2884
