### ISSUE TITLE
how to fix "panic: tls: first record does not look like a TLS handshake"

### ISSUE THREAD

**Issue by comerc** [ClickHouse/clickhouse-docs#1619]
https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/language-clients/go/index.md

пример кода `clickhouse-golang-example` ругается:

`panic: tls: first record does not look like a TLS handshake`

чтобы вылечить, нужно добавить в опции:

```go
			DialContext: func(ctx context.Context, addr string) (net.Conn, error) {
				var d net.Dialer
				return d.DialContext(ctx, "tcp", addr)
			},
```

**Comment by johnnymatthews** [comment]
Translation (square brackets [] are my assumptions):

> https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/integrations/language-clients/go/index.md
> 
> example code `clickhouse-golang-example` swears [returns?]:
> 
> ```
> panic: tls: first record does not look like a TLS handshake
> ```
> 
> to cure [fix?], you need to add to the options:
> 
> 			DialContext: func(ctx context.Context, addr string) (net.Conn, error) {
> 				var d net.Dialer
> 				return d.DialContext(ctx, "tcp", addr)
> 			},

It looks like this doc has already been updated to add the above options. Gonna close this one.
