### ISSUE TITLE
Remove experimental setting from Projections docs

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#167]
It appears you no longer need to set `allow_experimental_projection_optimization` to use projections. Let's verify, then remove it from the docs: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#projections

**Comment by DanRoscigno** [comment]
closed by https://github.com/ClickHouse/clickhouse-docs/issues/167
