### ISSUE TITLE
Assign Cloud Troubleshoot Tips page to the sidebar.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1676]
We have a Troubleshooting page specifically for Cloud users, but it's a bit out of date and need improving: https://clickhouse.com/docs/en/faq/troubleshooting

One quick win is assigning it to the sidebar, since it's currently not there at all and is acting as an _unlisted_ page.

**Comment by Felixoid** [comment]
I follow and update this page from the `Installation` perspective. And it looks very much updated.

Can't say something regarding the Cloud part. The part below looks valid. Maybe it's not full, for sure.

**Comment by johnnymatthews** [comment]
I've added this page to the sidebar under Cloud -> Get Started -> Troubleshooting. Does this seem appropriate @Felixoid ?

![Screenshot 2023-12-07 at 10 15 25](https://github.com/ClickHouse/clickhouse-docs/assets/9611008/0b2f498c-8d1a-48bb-8e60-59bcd09a83a5)

The URL remains the same: `/docs/en/faq/troubleshooting`.

**Comment by johnnymatthews** [comment]
Hmmm, not a fan of duplicate pages. I'll take a look at our analytics and see which page gets more views. The page with the most views gets to stay live; the other gets deleted and a redirect added.

**Comment by Felixoid** [comment]
We can split it in two, why not?

**Comment by johnnymatthews** [comment]
> We can split it in two, why not?

Yeah that'll probably work.

**Comment by Felixoid** [comment]
https://clickhouse.com/docs/knowledgebase/troubleshooting is gone

**Comment by johnnymatthews** [comment]
> It looks like the search cache is broken.

Turns out that Algolia only indexes the site once a day.

**Comment by Felixoid** [comment]
Hmm, it looks like an issue to me

The old link from https://github.com/ClickHouse/ClickHouse/issues/41420#issuecomment-1328773190 is broken
