### ISSUE TITLE
Remove unnecessary text

### ISSUE THREAD

**Issue by natalyjazzviolin** [ClickHouse/clickhouse-docs#1679]
Extra text is displayed by accident at [link](https://clickhouse.com/docs/category/%D0%B2%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5), it should be removed:
- otlichitelnye-vozmozhnosti-clickhouse}
- proizvoditelnost}
- istoriia-clickhouse}
<img width="1427" alt="Screenshot 2023-11-15 at 4 37 28 PM" src="https://github.com/ClickHouse/clickhouse-docs/assets/65251165/3a311339-b55d-4d2e-bc87-fa6c5809f4a5">

**Comment by johnnymatthews** [comment]
@natalyjazzviolin could you check my spelling/grammar/formatting in https://github.com/ClickHouse/ClickHouse/pull/56821? I used Google Translate, so it may have missed something.

**Comment by natalyjazzviolin** [comment]
@johnnymatthews LGTM! Thank you!
