### ISSUE TITLE
Explain what "parts" are.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1680]
Taken from the [Advanced tutorial](https://clickhouse.com/docs/en/tutorial):

> 6 just happens to be the number of parts that the trips table currently has, and parts know how many rows they have.

Up until this point, _parts_ haven't been mentioned or explained. Folks new to ClickHouse, or DB management in general, might not be familiar with _parts_ already.

**Comment by tom-clickhouse** [comment]
Fixed by #2929
