### ISSUE TITLE
Document missing functions `corrMatrix`, `corrStable`, `covarPopMatrix`, `covarSampMatrix`.

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#1682]
I found a few functions that do not appear to have documentation:

- [x]  corrMatrix
- [ ] corrStable
- [ ] covarPopMatrix
- [ ] covarSampMatrix

This PR is part of the culprit: https://github.com/ClickHouse/ClickHouse/issues/44587

**Comment by johnnymatthews** [comment]
Superseded by #1937 and #1939.
