### ISSUE TITLE
Fix broken Node.js link in `clickhouse.cloud/integrations/nodejs`.

### ISSUE THREAD

**Issue by pslootweg** [ClickHouse/clickhouse-docs#1688]
See https://clickhouse.com/docs/en/integrations/language-clients/nodejs which links from https://clickhouse.cloud/integrations/nodejs

**Comment by johnnymatthews** [comment]
Probably best to fix the link at the source rather than apply a redirect for this. I'll get on that. Thanks for raising @pslootweg!

**Comment by johnnymatthews** [comment]
I've submitted a change request to the Cloud team. They're gonna update the links shortly.

**Comment by johnnymatthews** [comment]
Looks like these borked links have been updated in ClickHouse Cloud. Closing.
