### ISSUE TITLE
Broken link on aws marketplace page

### ISSUE THREAD

**Issue by svoctor** [ClickHouse/clickhouse-docs#1695]
The product video link on the [aws marketplace](https://aws.amazon.com/marketplace/pp/prodview-jettukeanwrfc) page is broken. Link currently goes to: https://clickhouse.com/docs/en/home

That page does not seem to exist anymore.

**Comment by johnnymatthews** [comment]
Hmm, it's weird that a _video_ link is trying to take users to the docs. It's probably better if we point folks towards https://www.youtube.com/watch?v=FtoWGT7kS-c

**Comment by johnnymatthews** [comment]
Looks like this has been fixed. Closing.
