### ISSUE TITLE
KB -  How to implement pivot (like in pandas)?

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1716]
Taken from #7 .

From SO:

---

In ClickHouse, there isn't a direct equivalent to the `pivot` function in pandas. However, you can achieve similar results by using a combination of `groupArray` and `arrayJoin` functions. 

Here is an example of how you can do it:

1. First, create a table with your data. For instance, let's create a table named `xxx` with columns `Tag`, `Slot`, and `Reading`:

```sql
CREATE TABLE xxx (Tag String, Slot Int64, Reading Int64) Engine=Memory;
INSERT INTO xxx VALUES 
('A',1,5),
('B',1,6), 
('C',1,1), 
('A',2,2), 
('B',2,8),
('C',3,2);
```

2. Then, you can use the `groupArray` function to group the data by `Slot` and `Tag`:

```sql
SELECT
   Slot,
   groupArray((Tag, Reading))
FROM xxx
GROUP BY Slot
```

This will return a table where each row represents a `Slot`, and the `groupArray` column contains an array of tuples, each containing a `Tag` and its corresponding `Reading`.

Another approach is to use the `arrayJoin` function in combination with `groupArray` and `arrayEnumerate`. This approach is more complex but allows for more flexibility. Here is an example:

1. Create a table named `pivot_test` with columns `orderNum`, `s`, and `values`:

```sql
CREATE TABLE test.pivot_test
(   
   orderNum Int,
   s String,
   values Array(String)
) ENGINE = Memory;
INSERT INTO test.pivot_test
VALUES 
 (1, 'foo', ['one', 'one', 'one', 'two', 'two', 'two']),
 (3, 'baz', ['1', '2', '3', '4', '5', '6']),
 (4, 'zoo', ['x', 'y', 'z', 'q', 'w', 't']),
 (2, 'bar', ['A', 'B', 'C', 'A', 'B', 'C']);
```

2. Then, use the `arrayJoin` function to join the `values` array and `arrayEnumerate` to get the index of each value in the array. Then, use `groupArray` to group the values by their index:

```sql
SELECT arrayMap(x -> x.1, arraySort(x -> x.2, groupArray(value_ordernum))) as row
FROM
(
   SELECT
       (value, orderNum) AS value_ordernum,
       value_index
   FROM test.pivot_test
   ARRAY JOIN
       values AS value,
       arrayEnumerate(values) AS value_index
)
GROUP BY value_index;
```

This will return a table where each row represents a row of the original data, with the values of each column in the original data represented as an array.

**Comment by mneedham** [comment]
https://clickhouse.com/docs/knowledgebase/pivot
