### ISSUE TITLE
I want to be involved in document translation

### ISSUE THREAD

**Issue by clnliuhao** [ClickHouse/clickhouse-docs#1773]
I am a user from China. I found that some of the Chinese versions of the documents were missing or outdated. Below the Chinese version of the page is old, for example, https://clickhouse.com/docs/en/intro. The Chinese version of the page is missing, https://clickhouse.com/docs/en/operations/system-tables/query_log.
I noticed that the document directory structure in the English version is slightly different from the Chinese version, so I don't know how to start the translation work or what are your plans. I would like to know more about this.

**Comment by johnnymatthews** [comment]
Yeah, sorry about the Chinese docs being outdated. It's something we're aware of.

Translating the docs is a huge task, and it's not feasible or scaleable to do it manually. We're working on automatically translating the docs into Chinese (and other languages) as we speak. While we won't need help from users to manually translate the docs, we could certainly use your help verifying that the translations are accurate!

What's the best way to contact you @clnliuhao?
