### ISSUE TITLE
Add YepCode to integrations

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#1789]
https://twitter.com/yepcode_io/status/1737771390038880663

**Comment by johnnymatthews** [comment]
Already listed in https://clickhouse.com/docs/en/integrations, but we were missing a logo.



Logo added in [24573f4](https://github.com/ClickHouse/clickhouse-docs/commit/24573f43c7320bacffe524f48756d91eba837bbe). Closing.
