### ISSUE TITLE
Review and potentially update branching factor statement in sparse primary indexes.

### ISSUE THREAD

**Issue by petr-larin** [ClickHouse/clickhouse-docs#1793]
Here
[An index design for massive data scales](https://clickhouse.com/docs/en/optimize/sparse-primary-indexes#an-index-design-for-massive-data-scales)

we read that 
"Searching an entry in a B(+)-Tree data structure has average time complexity of O(log2 n). For a table of 8.87 million rows, this means **23 steps are required to locate any index entry.**"

23 steps would be correct if the b-tree had the branching factor of 2 (a binary tree), however, in reality the factor is some hundreds or thousands, so for this table, just 4 steps would be enough to find the right leaf.

**Comment by petr-larin** [comment]
I have proposed a simple edit and opened a PR, who can approve/reject it? Thank you!

**Comment by johnnymatthews** [comment]
Hey @petr-larin, thanks for the PR! It's in the _review queue_; we'll get to it shortly.

**Comment by petr-larin** [comment]
Pull request successfully merged and closed
https://github.com/ClickHouse/clickhouse-docs/pull/1830
