### ISSUE TITLE
Send users to `/docs` when visiting `docs.clickhouse.com`.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1797]
If you visit docs.clickhouse.com you get redirected to `/docs/en/intro` instead of `/docs`. Fix the redirect so that users end up at `/docs` when going to docs.clickhouse.com.

**Comment by justindeguzman** [comment]
@Felixoid do you possibly know where the `docs.clickhouse.com` redirect is being defined? It is not in the [Cloudflare worker](https://github.com/clickhouse/clickhouse-website-worker) where I would expect it the or [marketing website repo](https://github.com/clickhouse/marketing-website).

**Comment by Felixoid** [comment]
Discussed in slack

Now `docs.clickhouse.com/*` redirects to `https://clickhouse.com/docs/en/$1`

```
> curl -I https://docs.clickhouse.com/intro
HTTP/2 301
date: Tue, 23 Jan 2024 19:02:56 GMT
location: https://clickhouse.com/docs/en/intro
cache-control: max-age=3600
expires: Tue, 23 Jan 2024 20:02:56 GMT
strict-transport-security: max-age=0; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 84a24b3a4d1c6a6b-HAM
alt-svc: h3=":443"; ma=86400
```

Justin and Johnny agreed that it should be `https://clickhouse.com/docs/$1`

The changes are committed, here's how it looks now

```
> curl -I https://docs.clickhouse.com/intro
HTTP/2 301
date: Tue, 23 Jan 2024 19:03:01 GMT
location: https://clickhouse.com/docs/intro
cache-control: max-age=3600
expires: Tue, 23 Jan 2024 20:03:01 GMT
strict-transport-security: max-age=0; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 84a24b5adf8e630b-HAM
alt-svc: h3=":443"; ma=86400
```
