### ISSUE TITLE
Clarify how assigning users to issues works.

### ISSUE THREAD

**Issue by mbaksheev** [ClickHouse/clickhouse-docs#1817]
According to the contributing guide:

> If there isn't an issue for the specific thing you want to work on, quickly create one and assign yourself to it.

I created an issues and I'd like to work on it. But It looks like I don't have permissions to assign myself to the issue :(

**Comment by johnnymatthews** [comment]
Ah yeah sorry, looks like you can't assign issues within `clickhouse/clickhouse-docs` unless you're part of the `github.com/clickhouse` organization. We should rewrite the contributor guide to say:

> If there isn't an issue for the specific thing you want to work on, quickly create one and leave a comment in it asking for it to be assigned to you. A maintainer of this repository will add you as an assignee.

Which issue would you like to work on @mbaksheev? I can add you as an assignee.

**Comment by mbaksheev** [comment]
Currently I'm working on #1805
