### ISSUE TITLE
Document Cloud specific settings

### ISSUE THREAD

**Issue by jaijhala** [ClickHouse/clickhouse-docs#1823]
Issue: Currently we document all the settings [here](https://clickhouse.com/docs/en/operations/settings), specifically Server related settings are here -> https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings

But some of these settings default values are different in Cloud which can be confusing to users. 
We should document this better. 

For example: `max_table_size_to_drop`
It's default value is 50GB for on-prem but on Cloud this is set to 1TB. 

Possible solutions: 

1). Maybe in the same section, include On-prem and Cloud values if they're different. 
2). Have a dedicated settings section for Cloud docs, for example - https://clickhouse.com/docs/en/manage/settings

CC @justindeguzman

**Comment by justindeguzman** [comment]
Hi @jaijhala, do you have a list of cloud settings with different default values than OSS? We can add those.

**Comment by jaijhala** [comment]
hey @justindeguzman 

So I ran below query on a Cloud service: 

`select * from system.settings where changed` and exported into a file: 
[settings.CSV](https://github.com/ClickHouse/clickhouse-docs/files/13837030/settings.CSV)

There's about 40 rows, we can update the parameters that are already documented in our docs.

**Comment by justindeguzman** [comment]
PRs related to this issue have been submitted here:
https://github.com/ClickHouse/ClickHouse/pull/59783
https://github.com/ClickHouse/ClickHouse/pull/59784
https://github.com/ClickHouse/ClickHouse/pull/59785
https://github.com/ClickHouse/ClickHouse/pull/59786
