### ISSUE TITLE
Document all ClickHouse functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1833]
## Problem

There are many functions in ClickHouse, but not all are documented. See https://github.com/ClickHouse/clickhouse-docs/issues/1682 https://github.com/ClickHouse/clickhouse-docs/issues/1512 as examples. This issue serves as the main holding-issue for many child/sub-issues.  Essentially, if you want to know which functions have recently had documentation added, you should treat this issue as the source-of-truth.

## Solution

Document 100% of the functions in ClickHouse.

## Process

1. List all the functions that exist in ClickHouse.
2. List all the functions that have docs.
3. Create a list of functions that don't have docs.
4. Loop through this new list to write a description and syntax example for each function.
    1. To get this info, check the tests that each function was written with.
    2. Check in with the author of each function to get a background on why it was created.
5. Repeat step 4 until all the functions have docs.

## Scope

List each function, what it does, and a syntax example.

### Example

Here is a markdown example of what a function should look like the following (a copy of this is available in the [clickhouse/clickhouse](https://github.com/clickhouse/clickhouse) repository at `/docs/en/sql-reference/functions/_function-template.md`):

````markdown
## Example

This function serves as an example of what function documentation should look like.

**Syntax**

```sql
Example(input, secondary_input)
```

**Parameters**

- `input`: This is an example input. [String literal](../syntax#syntax-string-literal)
- `secondary_input`: This is another example input. [Expression](../syntax#syntax-expressions)

**Returned value**

This function doesn't exists. But if it did, they it would return a bool.

**Implementation details**

Any additional information pertaining to this function that users might need to know about. Things like known-bugs or edge cases would fit into this section. For example, if a function used _bankers rounding_ instead of standard rounding.

**Example**

Query:

```sql
CREATE TABLE example_table
(
    id UUID,
    name String,
) ENGINE = MergeTree
ORDER BY id;

INSERT INTO example_table VALUES (generateUUIDv4(), Example());
SELECT * FROM example_table;
```

```response
9e22db8c-d343-4bc5-8a95-501f635c0fc4	Example
```
````

Things to note:

1. The arguments must end in a valid type and link to that type within the docs.
2. The example query must be valid and complete; a user should be able to copy and paste the query directly into fiddle.clickhouse.com and have the query run without any modifications.
3. The example result must be _similar_ to what the user can expect to see when running it in fiddle.clickhouse.com. Some functions, such as `generateUUIDv4()`, will return a random string; as such, you shouldn't try to have your example response match what the user might see.

## Out of scope

We will not:

- Create a fancy new way of searching through functions.
- Expand on or update existing function docs.
- Create in-depth guides or tutorials for each function.
- Add docs directly into [clickhouse/clickhouse](https://github.com/clickhouse/clickhouse) code.
- Showcase specific functions.

These items are valid points to improve the docs, but they're entirely separate projects that require planning and setup of their own.

## Timeline

This project should be completed in Q1 2024. So, by the end of March 2024.

**Comment by johnnymatthews** [comment]
After going through all the available ClickHouse functions, and searching through the docs for appropriate documentation, I've concluded that we have **449 functions without adequate documentation**. See [this Google Sheet](https://docs.google.com/spreadsheets/d/1ChperqjgdJ9ic4HvzZYp7KhQ-ahFxYx3yw86ig3zZ0s/edit?usp=sharing).

449 function is _a lot_, especially given the size of the docs team. Without significant crowd-sourcing methods, it's unlikely that we'll get all of these missing functions documented by the end of March 2024.

**Comment by johnnymatthews** [comment]
Here's a complete list of the missing functions:

- [ ] FROM_UNIXTIME
- [ ] JSON_QUERY
- [ ] JSON_VALUE
- [ ] L2SquaredNorm
- [ ] TimeDiff
- [ ] UTC_timestamp
- [ ] VAR_POP
- [ ] VAR_SAMP
- [ ] YEAR
- [ ] __bitBoolMaskAnd
- [ ] __bitBoolMaskOr
- [ ] __bitSwapLastTwo
- [ ] __bitWrapperFunc
- [ ] __getScalar
- [ ] addTupleOfIntervals
- [ ] aggThrow
- [ ] analysisOfVariance
- [ ] and
- [ ] anova
- [ ] anyLast_respect_nulls
- [ ] any_respect_nulls
- [ ] any_value
- [ ] any_value_respect_nulls
- [ ] array
- [ ] arrayDotProduct
- [ ] arrayEnumerateDenseRanked
- [ ] arrayEnumerateUniqRanked
- [ ] arrayFirstOrNull
- [ ] arrayFlatten
- [ ] arrayLastOrNull
- [ ] arrayPartialShuffle
- [ ] arrayShuffle
- [ ] caseWithExpr
- [ ] caseWithExpression
- [ ] caseWithoutExpr
- [ ] caseWithoutExpression
- [ ] connectionId
- [ ] connection_id
- [ ] corrMatrix
- [ ] corrStable
- [ ] countMatchesCaseInsensitive
- [ ] countSubstringsCaseInsensitive
- [ ] countSubstringsCaseInsensitiveUTF8
- [ ] covarPopMatrix
- [ ] covarPopStable
- [ ] covarSampMatrix
- [ ] covarSampStable
- [ ] cramersVBiasCorrected
- [ ] currentSchemas
- [ ] current_schemas
- [ ] cutToFirstSignificantSubdomainCustomRFC
- [ ] cutToFirstSignificantSubdomainCustomWithWWWRFC
- [ ] cutToFirstSignificantSubdomainRFC
- [ ] cutToFirstSignificantSubdomainWithWWWRFC
- [ ] dense_rank
- [ ] detectProgrammingLanguage
- [ ] detectTonality
- [ ] dictGet
- [ ] dictGetDate
- [ ] dictGetDateOrDefault
- [ ] dictGetDateTime
- [ ] dictGetDateTimeOrDefault
- [ ] dictGetFloat32
- [ ] dictGetFloat32OrDefault
- [ ] dictGetFloat64
- [ ] dictGetFloat64OrDefault
- [ ] dictGetIPv4
- [ ] dictGetIPv4OrDefault
- [ ] dictGetIPv6
- [ ] dictGetIPv6OrDefault
- [ ] dictGetInt16
- [ ] dictGetInt16OrDefault
- [ ] dictGetInt32
- [ ] dictGetInt32OrDefault
- [ ] dictGetInt64
- [ ] dictGetInt64OrDefault
- [ ] dictGetInt8
- [ ] dictGetInt8OrDefault
- [ ] dictGetString
- [ ] dictGetStringOrDefault
- [ ] dictGetUInt16
- [ ] dictGetUInt16OrDefault
- [ ] dictGetUInt32
- [ ] dictGetUInt32OrDefault
- [ ] dictGetUInt64
- [ ] dictGetUInt64OrDefault
- [ ] dictGetUInt8
- [ ] dictGetUInt8OrDefault
- [ ] dictGetUUID
- [ ] dictGetUUIDOrDefault
- [ ] displayName
- [ ] domainRFC
- [ ] domainWithoutWWWRFC
- [ ] e
- [ ] emptyArrayFloat32
- [ ] emptyArrayFloat64
- [ ] emptyArrayInt16
- [ ] emptyArrayInt32
- [ ] emptyArrayInt64
- [ ] emptyArrayInt8
- [ ] emptyArrayString
- [ ] emptyArrayToSingle
- [ ] emptyArrayUInt16
- [ ] emptyArrayUInt32
- [ ] emptyArrayUInt64
- [ ] emptyArrayUInt8
- [ ] exp
- [ ] exponentialTimeDecayedAvg
- [ ] exponentialTimeDecayedCount
- [ ] exponentialTimeDecayedMax
- [ ] exponentialTimeDecayedSum
- [ ] extract
- [ ] extractGroups
- [ ] filesystemUnreserved
- [ ] firstSignificantSubdomainCustomRFC
- [ ] firstSignificantSubdomainRFC
- [ ] first_value_respect_nulls
- [ ] flameGraph
- [ ] flattenTuple
- [ ] formatQueryOrNull
- [ ] formatQuerySingleLineOrNull
- [ ] fromUnixTimestamp64Micro
- [ ] fromUnixTimestamp64Milli
- [ ] fullHostName
- [ ] getSubcolumn
- [ ] getTypeSerializationStreams
- [ ] globalIn
- [ ] globalInIgnoreSet
- [ ] globalNotIn
- [ ] globalNotInIgnoreSet
- [ ] globalNotNullIn
- [ ] globalNotNullInIgnoreSet
- [ ] globalNullIn
- [ ] globalNullInIgnoreSet
- [ ] globalVariable
- [ ] greater
- [ ] hasColumnInTable
- [ ] hasSubsequenceCaseInsensitive
- [ ] hasSubsequenceCaseInsensitiveUTF8
- [ ] hasSubsequenceUTF8
- [ ] hasThreadFuzzer
- [ ] hasToken
- [ ] hasTokenCaseInsensitive
- [ ] hasTokenCaseInsensitiveOrNull
- [ ] hasTokenOrNull
- [ ] ignore
- [ ] in
- [ ] inIgnoreSet
- [ ] initcap
- [ ] intHash32
- [ ] intHash64
- [ ] isNotDistinctFrom
- [ ] isNullable
- [ ] joinGetOrNull
- [ ] kostikConsistentHash
- [ ] kql_array_sort_asc
- [ ] kql_array_sort_desc
- [ ] lagInFrame
- [ ] last_value_respect_nulls
- [ ] lcase
- [ ] leadInFrame
- [ ] left
- [ ] leftUTF8
- [ ] lengthUTF8
- [ ] less
- [ ] lessOrEquals
- [ ] lowCardinalityIndices
- [ ] lowCardinalityKeys
- [ ] makeDate32
- [ ] makeDateTime64
- [ ] mapPartialReverseSort
- [ ] mapPartialSort
- [ ] materialize
- [ ] maxMappedArrays
- [ ] minMappedArrays
- [ ] moduloLegacy
- [ ] mortonDecode
- [ ] mortonEncode
- [ ] multiSearchAllPositionsCaseInsensitive
- [ ] multiSearchAllPositionsCaseInsensitiveUTF8
- [ ] multiSearchAllPositionsUTF8
- [ ] multiSearchAnyCaseInsensitive
- [ ] multiSearchAnyCaseInsensitiveUTF8
- [ ] multiSearchAnyUTF8
- [ ] multiSearchFirstIndexCaseInsensitive
- [ ] multiSearchFirstIndexCaseInsensitiveUTF8
- [ ] multiSearchFirstIndexUTF8
- [ ] multiSearchFirstPositionCaseInsensitive
- [ ] multiSearchFirstPositionCaseInsensitiveUTF8
- [ ] multiSearchFirstPositionUTF8
- [ ] ngramDistanceCaseInsensitive
- [ ] ngramDistanceCaseInsensitiveUTF8
- [ ] ngramDistanceUTF8
- [ ] ngramSearchCaseInsensitive
- [ ] ngramSearchCaseInsensitiveUTF8
- [ ] ngramSearchUTF8
- [ ] nonNegativeDerivative
- [ ] normL2Squared
- [ ] normalizeQueryKeepNames
- [ ] normalizedQueryHashKeepNames
- [ ] notInIgnoreSet
- [ ] notNullIn
- [ ] notNullInIgnoreSet
- [ ] nth_value
- [ ] nullIn
- [ ] nullInIgnoreSet
- [ ] or
- [ ] partitionId
- [ ] portRFC
- [ ] proportionsZTest
- [ ] protocol
- [ ] rand
- [ ] rand32
- [ ] rand64
- [ ] randCanonical
- [ ] rank
- [ ] readWKTPoint
- [ ] readWKTRing
- [ ] regionHierarchy
- [ ] regionIn
- [ ] regionToArea
- [ ] regionToCity
- [ ] regionToContinent
- [ ] regionToCountry
- [ ] regionToDistrict
- [ ] regionToName
- [ ] regionToPopulation
- [ ] regionToTopContinent
- [ ] reinterpretAsDate
- [ ] reinterpretAsDateTime
- [ ] reinterpretAsFixedString
- [ ] reinterpretAsFloat32
- [ ] reinterpretAsFloat64
- [ ] reinterpretAsInt128
- [ ] reinterpretAsInt16
- [ ] reinterpretAsInt256
- [ ] reinterpretAsInt32
- [ ] reinterpretAsInt64
- [ ] reinterpretAsInt8
- [ ] reinterpretAsString
- [ ] reinterpretAsUInt128
- [ ] reinterpretAsUInt16
- [ ] reinterpretAsUInt256
- [ ] reinterpretAsUInt32
- [ ] reinterpretAsUInt64
- [ ] reinterpretAsUInt8
- [ ] reinterpretAsUUID
- [ ] reverseDNSQuery
- [ ] revision
- [ ] right
- [ ] rightUTF8
- [ ] roundAge
- [ ] roundDown
- [ ] roundDuration
- [ ] roundToExp2
- [ ] rowNumberInAllBlocks
- [ ] rowNumberInBlock
- [ ] row_number
- [ ] showCertificate
- [ ] sigmoid
- [ ] simpleJSONExtractBool
- [ ] simpleJSONExtractFloat
- [ ] simpleJSONExtractInt
- [ ] simpleJSONExtractRaw
- [ ] simpleJSONExtractString
- [ ] simpleJSONExtractUInt
- [ ] simpleJSONHas
- [ ] sin
- [ ] singleValueOrNull
- [ ] sleep
- [ ] sleepEachRow
- [ ] stddevPop
- [ ] stddevPopStable
- [ ] stddevSamp
- [ ] stddevSampStable
- [ ] substringIndexUTF8
- [ ] substringUTF8
- [ ] subtractDays
- [ ] subtractHours
- [ ] subtractInterval
- [ ] subtractMicroseconds
- [ ] subtractMilliseconds
- [ ] subtractMinutes
- [ ] subtractMonths
- [ ] subtractNanoseconds
- [ ] subtractQuarters
- [ ] subtractSeconds
- [ ] subtractTupleOfIntervals
- [ ] subtractWeeks
- [ ] subtractYears
- [ ] sum
- [ ] sumMapFiltered
- [ ] sumMapFilteredWithOverflow
- [ ] sumMapWithOverflow
- [ ] sumWithOverflow
- [ ] svg
- [ ] tanh
- [ ] timeSlot
- [ ] timeSlots
- [ ] toBool
- [ ] toDateTime64OrDefault
- [ ] toDateTime64OrNull
- [ ] toDateTime64OrZero
- [ ] toDecimal128
- [ ] toDecimal128OrDefault
- [ ] toDecimal128OrNull
- [ ] toDecimal128OrZero
- [ ] toDecimal256
- [ ] toDecimal256OrDefault
- [ ] toDecimal256OrNull
- [ ] toDecimal256OrZero
- [ ] toDecimal32
- [ ] toDecimal32OrDefault
- [ ] toDecimal32OrNull
- [ ] toDecimal32OrZero
- [ ] toDecimal64
- [ ] toDecimal64OrDefault
- [ ] toDecimal64OrNull
- [ ] toDecimal64OrZero
- [ ] toDecimalString
- [ ] toFixedString
- [ ] toFloat32
- [ ] toFloat32OrDefault
- [ ] toFloat32OrNull
- [ ] toFloat32OrZero
- [ ] toFloat64
- [ ] toFloat64OrDefault
- [ ] toFloat64OrNull
- [ ] toFloat64OrZero
- [ ] toIPv4OrDefault
- [ ] toIPv4OrNull
- [ ] toIPv4OrZero
- [ ] toIPv6OrDefault
- [ ] toIPv6OrNull
- [ ] toIPv6OrZero
- [ ] toISOWeek
- [ ] toISOYear
- [ ] toInt128
- [ ] toInt128OrDefault
- [ ] toInt128OrNull
- [ ] toInt128OrZero
- [ ] toInt16
- [ ] toInt16OrDefault
- [ ] toInt16OrNull
- [ ] toInt16OrZero
- [ ] toInt256
- [ ] toInt256OrDefault
- [ ] toInt256OrNull
- [ ] toInt256OrZero
- [ ] toInt32
- [ ] toInt32OrDefault
- [ ] toInt32OrNull
- [ ] toInt32OrZero
- [ ] toInt64
- [ ] toInt64OrDefault
- [ ] toInt64OrNull
- [ ] toInt64OrZero
- [ ] toInt8
- [ ] toInt8OrDefault
- [ ] toInt8OrNull
- [ ] toInt8OrZero
- [ ] toIntervalDay
- [ ] toIntervalHour
- [ ] toIntervalMicrosecond
- [ ] toIntervalMillisecond
- [ ] toIntervalMinute
- [ ] toIntervalMonth
- [ ] toIntervalNanosecond
- [ ] toIntervalQuarter
- [ ] toIntervalSecond
- [ ] toIntervalWeek
- [ ] toIntervalYear
- [ ] toRelativeDayNum
- [ ] toRelativeHourNum
- [ ] toRelativeMinuteNum
- [ ] toRelativeMonthNum
- [ ] toRelativeQuarterNum
- [ ] toRelativeSecondNum
- [ ] toRelativeWeekNum
- [ ] toRelativeYearNum
- [ ] toStartOfMicrosecond
- [ ] toStartOfMillisecond
- [ ] toStartOfNanosecond
- [ ] toTime
- [ ] toTimezone
- [ ] toTypeName
- [ ] toUInt128
- [ ] toUInt128OrNull
- [ ] toUInt128OrZero
- [ ] toUInt16
- [ ] toUInt16OrDefault
- [ ] toUInt16OrNull
- [ ] toUInt16OrZero
- [ ] toUInt256
- [ ] toUInt256OrDefault
- [ ] toUInt256OrNull
- [ ] toUInt256OrZero
- [ ] toUInt32
- [ ] toUInt32OrDefault
- [ ] toUInt32OrNull
- [ ] toUInt32OrZero
- [ ] toUInt64
- [ ] toUInt64OrDefault
- [ ] toUInt64OrNull
- [ ] toUInt64OrZero
- [ ] toUInt8
- [ ] toUInt8OrDefault
- [ ] toUInt8OrNull
- [ ] toUInt8OrZero
- [ ] toUnixTimestamp64Micro
- [ ] toUnixTimestamp64Milli
- [ ] today
- [ ] topLevelDomainRFC
- [ ] transactionID
- [ ] transactionLatestSnapshot
- [ ] transactionOldestSnapshot
- [ ] translateUTF8
- [ ] trunc
- [ ] truncate
- [ ] tryBase58Decode
- [ ] tryBase64Decode
- [ ] tumbleEnd
- [ ] tumbleStart
- [ ] tupleIntDiv
- [ ] tupleIntDivByNumber
- [ ] tupleIntDivOrZero
- [ ] tupleIntDivOrZeroByNumber
- [ ] tupleModulo
- [ ] tupleModuloByNumber
- [ ] ucase
- [ ] uniqCombined64
- [ ] upper
- [ ] upperUTF8
- [ ] uptime
- [ ] validateNestedArraySizes
- [ ] varPopStable
- [ ] varSampStable
- [ ] version
- [ ] visitParamExtractBool
- [ ] visitParamExtractFloat
- [ ] visitParamExtractInt
- [ ] visitParamExtractRaw
- [ ] visitParamExtractString
- [ ] visitParamExtractUInt
- [ ] visitParamHas
- [ ] windowID
- [ ] wkt
- [ ] wyHash64
- [ ] yandexConsistentHash

**Comment by johnnymatthews** [comment]
Hey @Blargian, sorry for the delay in getting back to you. I've just seen a few comment and PRs from yourself, so thanks for that! If you're still interested in helping out, just keep plugging away at the issues. If you'd like specific issues to be assigned to yourself, just leave a comment in the issue saying something like _"I'll work on this one"_ -- I'll assign it to you then :)

**Comment by gingerwizard** [comment]
@Blargian can we close this?
