### ISSUE TITLE
Get around the dev verification error in MacOS.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1834]
When you install ClickHouse using `brew install --cask clickhouse` on MacOS, you get a lovely little _developer couldn't be verified_ error:

![dev-verification-error](https://github.com/ClickHouse/clickhouse-docs/assets/9611008/feb84627-e5b2-43ec-9cac-574d2f574b7e)

A workaround is to add the executable to MacOS's quarantine list.

**Comment by rschu1ze** [comment]
The actual way to fix this error would be to sign the binary with Apple's developer certificate. This doesn't mean that the binary is free of malware but that Apple knows you (as developer) and receives 99 $ yearly fee :-) I tried that last November but the the final signing step failed with obscure errors ... until then, a documented workaround is good.
