### ISSUE TITLE
Expand Tableau guide to use ClickHouse Cloud as well as a local ClickHouse service.

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-docs#1839]
https://clickhouse.com/docs/en/integrations/tableau provides an example of connection to localhost. The page should be extended to provide an example for a connection to ClickHouse Cloud as well.

**Comment by BentsiLeviav** [comment]
@mshustov We talked about it a few days ago (just want to make sure about it):
There is no difference between connecting to the cloud and the local instance (I followed the instructions provided in the doc and connected successfully to our cloud instance).

Having said that, do we want to add to our docs something in particular?

**Comment by mshustov** [comment]
The example in the docs needs a few adjustments 
- `server` - a cloud host
- `port` - ~8123~ 8443
- password is a required field
- SSL is required (I suspect so)

![2024-02-05_09-43-49](https://github.com/ClickHouse/clickhouse-docs/assets/3198181/60f93ba0-d81e-40fe-ab18-35a21ffa0daa)

**Comment by BentsiLeviav** [comment]
Detailed documentation was added in ClickHouse/clickhouse-docs#1911
