### ISSUE TITLE
Remove Table of Contents from "Writing Queries in ClickHouse using GitHub Data" page.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1861]
The page [Writing Queries in ClickHouse using GitHub Data](https://clickhouse.com/docs/en/getting-started/example-datasets/github#downloading-and-inserting-the-data) has a huge table of contents right at the top (hard coded into the markdown, not supplied by Docusaurus). This ToC doesn't actually work, and it unnecessary. It should be removed.

![image](https://github.com/ClickHouse/clickhouse-docs/assets/9611008/2ae8d43e-990d-4c2b-83f6-ebda807191c2)

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/ClickHouse/pull/73348
