### ISSUE TITLE
Add cell_towers dataset to S3 + insert from S3 example

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-docs#1862]
Similarly to [commits](https://clickhouse.com/docs/en/getting-started/example-datasets/github)

```sql
INSERT INTO git.commits SELECT *
FROM s3('https://datasets-documentation.s3.amazonaws.com/github/commits/clickhouse/commits.tsv.xz', 'TSV', 'hash String,author LowCardinality(String), time DateTime, message String, files_added UInt32, files_deleted UInt32, files_renamed UInt32, files_modified UInt32, lines_added UInt32, lines_deleted UInt32, hunks_added UInt32, hunks_removed UInt32, hunks_changed UInt32')
```

Which is convenient for local tests. If the dataset size is an issue, it can be reduced to a few years of historical data.

**Comment by gingerwizard** [comment]
@lio-p get the data, put in bucket, enrich docs https://clickhouse.com/docs/en/getting-started/example-datasets/cell-towers to show loading from s3
