### ISSUE TITLE
Fix overflow issue on Float32/64 type page.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1897]
There's an issue happening on Brave where the note callout is overflowing across the page:

![Screenshot 2024-02-01 at 10 45 04 AM](https://github.com/ClickHouse/clickhouse-docs/assets/9611008/11c293f1-15ee-478a-bfe9-21c8d643ac6c)

Page here: https://clickhouse.com/docs/en/sql-reference/data-types/float

I haven't tested this in any other browser. Just dropping in this issue while I'm working on other things.

**Comment by gingerwizard** [comment]
Closed https://github.com/ClickHouse/clickhouse-docs/pull/2909
