### ISSUE TITLE
Document `FROM_UNIXTIME` function

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1919]
Create documentation for the `FROM_UNIXTIME` function. See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
This is an alias for `fromUnixTImestamp` which exists here: 
https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#fromunixtimestamp

Closing issue.
