### ISSUE TITLE
Document `TimeDiff` function.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1922]
Create documentation for the `TimeDiff` function. See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I have written documentation for this function. Could you please tell me where I should open the PR? I wrote the documentation in `ClickHouse/docs` however if I open the PR there then I am unable to link to this issue in this `clickhouse-docs` repo.
