### ISSUE TITLE
Document `__bitXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1926]
Create documentation for the `__bitXYZ` functions:

- [ ] __bitBoolMaskAnd
- [ ] __bitBoolMaskOr
- [ ] __bitSwapLastTwo
- [ ] __bitWrapperFunc

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by irfan-iiitr** [comment]
I would like to contribute to this.
I have tried running the above functions in ClickHouse Cloud SQL Console to get more ideas about these functions.
I think I can now document about these functions.

**Comment by Blargian** [comment]
@irfan-iiitr That would be much appreciated! Give a shout if you need any help.

**Comment by irfan-iiitr** [comment]
Sure @Blargian , As this will be my first Contribution here, I will surely be needing some help .
The journey ahead will be smooth.

**Comment by irfan-iiitr** [comment]
Should I create a new file forall these 4 function or should I append in the  sql-reference/functions/bit-functions.md .
If i were to create a new file , What should i name it  as there are files with simila names present too.

**Comment by Blargian** [comment]
> @Blargian Should I create a new file forall these 4 function or should I append in the sql-reference/functions/bit-functions.md . If i were to create a new file , What should i name it as there are files with simila names present too.

Better to append to `bit-functions.md`. We try to have all functions in the documentation with the same formatting - you can see it [here](https://clickhouse.com/docs/en/sql-reference/functions/array-functions#empty) for example.

**Comment by irfan-iiitr** [comment]
Please Review this.  [PR](https://github.com/ClickHouse/ClickHouse/pull/66469)

**Comment by Blargian** [comment]
Closing as these functions are for internal use only. See [comment here](https://github.com/ClickHouse/ClickHouse/pull/66469#issuecomment-2230730877)
