### ISSUE TITLE
Document `anyXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1933]
Create documentation for the `anyXYZ` functions:

- [ ] anyLast_respect_nulls
- [ ] any_respect_nulls
- [ ] any_value
- [ ] any_value_respect_nulls

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I'll work on this one.
