### ISSUE TITLE
Document `arrayXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1934]
Create documentation for the `arrayXYZ` function: 

- [ ] array
- [ ] arrayDotProduct
- [ ] arrayEnumerateDenseRanked
- [ ] arrayEnumerateUniqRanked
- [ ] arrayFirstOrNull
- [ ] arrayFlatten
- [ ] arrayLastOrNull
- [ ] arrayPartialShuffle
- [ ] arrayShuffle

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I'll work on this one.

**Comment by Blargian** [comment]
- [ ]  array
- [X]  arrayDotProduct
- [ ]  arrayEnumerateDenseRanked
- [ ]  arrayEnumerateUniqRanked
- [ ]  arrayFirstOrNull
- [ ]  arrayFlatten
- [ ]  arrayLastOrNull
- [ ]  arrayPartialShuffle
- [ ]  arrayShuffle
