### ISSUE TITLE
Document `caseXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1935]
Create documentation for the `caseXYZ` function: 

- [ ] caseWithExpr
- [ ] caseWithExpression
- [ ] caseWithoutExpr
- [ ] caseWithoutExpression

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@alexey-milovidov we don't need to document these functions as they are not intended for direct use right?

**Comment by Blargian** [comment]
As per the comment [here](https://github.com/ClickHouse/ClickHouse/blob/696114ff1aacb7f75dde4a928c9c04b65c078bc2/src/Functions/caseWithExpression.cpp#L18) these functions should never be called by the user.
