### ISSUE TITLE
Document `connectionId` and `connection_id` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1936]
Create documentation for the `connectionId` and `connection_id` functions. See #1833 for details on how to complete this issue.

- [x] connectionId
- [x] connection_id

Child issue of #1833.

**Comment by vdimir** [comment]
Used only in MySQL handler for compatibility with MySQL's `CONNECTION_ID` function  (https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_connection-id)
