### ISSUE TITLE
Document `countXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1938]
Create documentation for the `countXYZ` function:

- [ ] countMatchesCaseInsensitive
- [ ] countSubstringsCaseInsensitive
- [ ] countSubstringsCaseInsensitiveUTF8

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
- [X]  countMatchesCaseInsensitive
- [X]  countSubstringsCaseInsensitive
- [X]  countSubstringsCaseInsensitiveUTF8
