### ISSUE TITLE
URL and attribution for the dbt connector

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/clickhouse-docs#194]
@guykoh , in the dbt integration docs we refer to the connector as community maintained.  Now that it is in the ClickHouse organization should we change that line in the docs and update the link?

https://clickhouse.com/docs/en/integrations/dbt/dbt-intro

**Comment by guykoh** [comment]
Yes, good catch, I'll update the docs

**Comment by mshustov** [comment]
https://clickhouse.com/docs/en/integrations/dbt/dbt-intro doesn't refer to DBT integration as the community one anymore, closing the issue.
