### ISSUE TITLE
Document `cutToFirstSignificantXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1942]
Create documentation for the `cutToFirstSignificantXYZ` functions. 

- [ ] cutToFirstSignificantSubdomainCustomRFC
- [ ] cutToFirstSignificantSubdomainCustomWithWWWRFC
- [x] cutToFirstSignificantSubdomainRFC
- [x] cutToFirstSignificantSubdomainWithWWWRFC

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by vdimir** [comment]
https://github.com/ClickHouse/ClickHouse/blob/512f0d233e79c05f007cbaba0aa6a235f63e930b/src/Functions/URL/cutToFirstSignificantSubdomainCustom.cpp#L43-L82
