### ISSUE TITLE
Document `expXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1949]
Create documentation for the `expXYZ` function: 

- [ ] exp
- [ ] exponentialTimeDecayedAvg
- [ ] exponentialTimeDecayedCount
- [ ] exponentialTimeDecayedMax
- [ ] exponentialTimeDecayedSum

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I'll pick this one up.

**Comment by Blargian** [comment]
@excitoon I'd like to add documentation for the following functions:

- exponentialTimeDecayedSum
- exponentialTimeDecayedMax
- exponentialTimeDecayedCount
- exponentialTimeDecayedAvg

As I saw they are all exponentially smoothed moving window functions. Could you tell me something about how Avg, Sum, Max and Count differ from each other?
