### ISSUE TITLE
Automatically scroll left-hand navigation to current link

### ISSUE THREAD

**Issue by justindeguzman** [ClickHouse/clickhouse-docs#1952]
When users navigate to a page, they are often confused about where they are in the docs directory. For example, if they navigate to the system tables overview page, they cannot see the entire list of system tables.

![image](https://github.com/ClickHouse/clickhouse-docs/assets/3936029/a5082445-5c2f-433a-9338-ec99540d7898)

![image](https://github.com/ClickHouse/clickhouse-docs/assets/3936029/dbe0e347-a9d0-4da7-a3d2-d811db2e4bc6)

The behavior for this fix should be the following: when the user navigates to a page, the left hand navigation should scroll (and not animate) to show the current matching link.

@guykoh @ArctypeZach I'll try a fix this week but this may be above my CSS skillset–is it possible to please have some Control Plane team help here?

cc @tbragin who brought up this issue

**Comment by guykoh** [comment]
Yeah, no problem @justindeguzman, @vineethasok can help you if you don't manage to solve it by yourself.
