### ISSUE TITLE
Document `flameGraph` function.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1954]
Create documentation for the `flameGraph` function. See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by vdimir** [comment]
Documentation in code comments: https://github.com/ClickHouse/ClickHouse/blob/5dd81f38fb512cf74b24f0be1e2b6ae40045e40d/src/AggregateFunctions/AggregateFunctionFlameGraph.cpp#L474-L522
