### ISSUE TITLE
Document `formatQueryXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1956]
Create documentation for the `formatQueryXYZ` functions 

- [ ] formatQueryOrNull
- [ ] formatQuerySingleLineOrNull

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
Documentation exists here:
[formatQueryOrNull](https://clickhouse.com/docs/en/sql-reference/functions/other-functions#formatquery)
[formatQuerySingleLineOrNull](https://clickhouse.com/docs/en/sql-reference/functions/other-functions#formatquerysingleline)
