### ISSUE TITLE
Document `hasXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1962]
Create documentation for the `hasXYZ` functions: 

- [ ] hasColumnInTable
- [ ] hasSubsequenceCaseInsensitive
- [ ] hasSubsequenceCaseInsensitiveUTF8
- [ ] hasSubsequenceUTF8
- [ ] hasThreadFuzzer
- [ ] hasToken
- [ ] hasTokenCaseInsensitive
- [ ] hasTokenCaseInsensitiveOrNull
- [ ] hasTokenOrNull

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I'll pick this one up

**Comment by Blargian** [comment]
- hasColumnInTable →functions/other
- hasSubsequenceCaseInsensitive →functions/string-search-functions
- hasSubsequenceCaseInsensitiveUTF8→ functions/string-search-functions
- hasSubsequenceUTF8 →functions/string-search-functions
- hasThreadFuzzer →doesn't exist yet
- hasToken → doesn't exist yet
- hasTokenCaseInsensitive →doesn't exist yet
- hasTokenCaseInsensitiveOrNull →doesn't exist yet
- hasTokenOrNull →doesn't exist yet

**Comment by Blargian** [comment]
@alexey-milovidov `hasThreadFuzzer` seems to be for internal use with CI tests. Should it still be documented?

**Comment by alexey-milovidov** [comment]
@Blargian You can provide minimal documentation for this function, explaining its purpose, so other people will not be surprised about it.
