### ISSUE TITLE
Document `inXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1964]
Create documentation for the `inXYZ` function: 

- [ ] in
- [ ] inIgnoreSet

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
[Found here](https://github.com/ClickHouse/ClickHouse/blob/ce4d88851a25fb3d3ba426fa047cb2482e70a9d8/src/Functions/in.cpp#L40) and defined along with the `GlobalIn` functions. These are all syntactic sugar, not intended to be called directly by users.
