### ISSUE TITLE
Document `kql_array_sortXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1970]
Create documentation for the `kql_array_sortXYZ` functions:

- [ ] kql_array_sort_asc
- [ ] kql_array_sort_desc

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@rschu1ze I notice that we don't currently have any documentation listing which [functions](https://github.com/ClickHouse/ClickHouse/blob/e1ad5c765268fca75258b83c9c701c387033eca7/src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp) are supported with KQL. Is it worth adding? If so where would be the best place to put that? 

As part of [this page](https://clickhouse.com/docs/en/guides/developer/alternative-query-languages#kusto-query-language-kql) perhaps?

**Comment by Blargian** [comment]
`kql_array_sort_asc` and `kql_array_sort_desc` appear to be used internally to implement `array_sort_asc` and `array_sort_desc` respectively, this is not a function the user will call so I don't think it needs to be documented.

**Comment by rschu1ze** [comment]
> @rschu1ze I notice that we don't currently have any documentation listing which [functions](https://github.com/ClickHouse/ClickHouse/blob/e1ad5c765268fca75258b83c9c701c387033eca7/src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp) are supported with KQL. Is it worth adding? If so where would be the best place to put that?
> 
> As part of [this page](https://clickhouse.com/docs/en/guides/developer/alternative-query-languages#kusto-query-language-kql) perhaps?

I know Kusto (KQL) unfortunately too little, in particularly I have no idea why not all functions are enabled in Kusto. Is there some conceptual reason for this (e.g. ClickHouse aims to replicate the functions in the Kusto spec, if there is such a thing)? Is the only reason that for some weird reason C++ function implementations must be "enabled" to be visible to Kusto, and if so why has this not be done for all functions? Really just speculating.

I guess, depending on whether
- 99 % of the SQL functions are also available in Kusto, or
- only 1% of the SQL functions are available in Kusto and 99% are not,
we should document the exceptions to the rule.

Anyways, perhaps @yakov-olkhovskiy has an opinion too?

**Comment by yakov-olkhovskiy** [comment]
These function were added as a part of unofficial project to support kusto dialect and since it is not finished yet no documentation was completed. We already have PR for third phase of this project, but I didn't review it yet (my bad, sorry). I will review possibility of creating documentation along with this phase.

**Comment by Blargian** [comment]
> These function were added as a part of unofficial project to support kusto dialect and since it is not finished yet no documentation was completed. We already have PR for third phase of this project, but I didn't review it yet (my bad, sorry). I will review possibility of creating documentation along with this phase.
> 
> 

@yakov-olkhovskiy thanks for clarifying, and feel free to tag me if I can help out with the documentation anyhow.
