### ISSUE TITLE
Document `lessXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1977]
Create documentation for the `lessXYZ` functions:

- [ ] less
- [ ] lessOrEquals

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
These are [operator functions](https://clickhouse.com/docs/en/sql-reference/operators#less-function), I'm not sure we need to document them in more detail than they already are.
