### ISSUE TITLE
Document `multiSearchXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1985]
Create documentation for the `multiSearchXYZ` functions:

- [ ] multiSearchAllPositionsCaseInsensitive
- [ ] multiSearchAllPositionsCaseInsensitiveUTF8
- [ ] multiSearchAllPositionsUTF8
- [ ] multiSearchAnyCaseInsensitive
- [ ] multiSearchAnyCaseInsensitiveUTF8
- [ ] multiSearchAnyUTF8
- [ ] multiSearchFirstIndexCaseInsensitive
- [ ] multiSearchFirstIndexCaseInsensitiveUTF8
- [ ] multiSearchFirstIndexUTF8
- [ ] multiSearchFirstPositionCaseInsensitive
- [ ] multiSearchFirstPositionCaseInsensitiveUTF8
- [ ] multiSearchFirstPositionUTF8

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I'll pick this one up

**Comment by Blargian** [comment]
- [X]  multiSearchAllPositionsCaseInsensitive
- [X]  multiSearchAllPositionsCaseInsensitiveUTF8
- [X]  multiSearchAllPositionsUTF8
- [X]  multiSearchAnyCaseInsensitive
- [X]  multiSearchAnyCaseInsensitiveUTF8
- [X]  multiSearchAnyUTF8
- []  multiSearchFirstIndexCaseInsensitive
- [ ]  multiSearchFirstIndexCaseInsensitiveUTF8
- [ ]  multiSearchFirstIndexUTF8
- [ ]  multiSearchFirstPositionCaseInsensitive
- [ ]  multiSearchFirstPositionCaseInsensitiveUTF8
- [ ]  multiSearchFirstPositionUTF8
