### ISSUE TITLE
Document `ngramXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1986]
Create documentation for the `ngramXYZ` functions:

- [ ] ngramDistanceCaseInsensitive
- [ ] ngramDistanceCaseInsensitiveUTF8
- [ ] ngramDistanceUTF8
- [ ] ngramSearchCaseInsensitive
- [ ] ngramSearchCaseInsensitiveUTF8
- [ ] ngramSearchUTF8

See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I'll work on this one

**Comment by Blargian** [comment]
- [X]  ngramDistanceCaseInsensitive
- [X]  ngramDistanceCaseInsensitiveUTF8
- [X]  ngramDistanceUTF8
- [ ]  ngramSearchCaseInsensitive
- [ ]  ngramSearchCaseInsensitiveUTF8
- [ ]  ngramSearchUTF8
