### ISSUE TITLE
Document `notXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1990]
Create documentation for the `notXYZ` functions. See #1833 for details on how to complete this issue.

- [ ] notInIgnoreSet
- [ ] notNullIn
- [ ] notNullInIgnoreSet

Child issue of #1833.

**Comment by Blargian** [comment]
Closing as these are syntactic sugar, there is no need to document. See [comment](https://github.com/ClickHouse/ClickHouse/pull/66430#discussion_r1675700573)
