### ISSUE TITLE
Document `nullInXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1992]
Create documentation for the `nullInXYZ` functions. See #1833 for details on how to complete this issue.

- [ ] nullIn
- [ ] nullInIgnoreSet

Child issue of #1833.

**Comment by Blargian** [comment]
[Found here](https://github.com/ClickHouse/ClickHouse/blob/ce4d88851a25fb3d3ba426fa047cb2482e70a9d8/src/Functions/in.cpp#L35) together with `GlobalIn`, 'InIgnoreSet' etc. These we decided not to document as they are syntactic sugar.
