### ISSUE TITLE
Document `regionXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2001]
Create documentation for the `regionXYX` functions. See #1833 for details on how to complete this issue.

- [x] regionHierarchy
- [x] regionIn
- [x] regionToArea
- [x] regionToCity
- [x] regionToContinent
- [x] regionToCountry
- [x] regionToDistrict
- [x] regionToName
- [x] regionToPopulation
- [x] regionToTopContinent

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I'll work on this one

**Comment by Blargian** [comment]
@alexey-milovidov I'm working on this issue and thought it will be nice to have some examples the user can follow with minimal setup. Are full `regions_hierarchy.txt` and `regions_hierarchy_ua.txt` referred to in the documentation [here](https://clickhouse.com/docs/en/sql-reference/functions/ym-dict-functions#regiontoareaid-geobase) available somewhere to be downloaded and used?

**Comment by Blargian** [comment]
Relevant sections of the docs:
- [multiple-geobases](https://clickhouse.com/docs/en/sql-reference/functions/ym-dict-functions#multiple-geobases)
- [embedded-dictionaries](https://clickhouse.com/docs/en/sql-reference/dictionaries#embedded-dictionaries)

This seems like an older feature from Yandex days. Geobases such as the one used in the documentation are Yandex proprietary content so it is necessary to make your own ones. I'd like to rewrite this section of the docs with a geobase available that the user can download and use to try out this feature. 

- [ ] Link to the embedded dictionaries page on the multiple geobases page (currently there is no link).
- [X] Create own regions_hierarchy file for use in examples.
- [ ] Try get it working [62363](https://github.com/ClickHouse/ClickHouse/issues/62363)
- [ ] Rewrite documentation to use the example
- [ ] Find out if we can host the files somewhere to download

**Comment by alexey-milovidov** [comment]
Yes, these are obsolete functions. It will be enough to provide minimal examples, which you can find in our tests.

**Comment by Blargian** [comment]
- [X]  regionHierarchy
- [X]  regionIn
- [X]  regionToArea
- [X]  regionToCity
- [X]  regionToContinent
- [X]  regionToCountry
- [X]  regionToDistrict
- [X]  regionToName
- [X]  regionToPopulation
- [X]  regionToTopContinent
