### ISSUE TITLE
Document `rightXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2005]
Create documentation for the `rightXYZ` function. See #1833 for details on how to complete this issue.

- [ ] right
- [ ] rightUTF8

Child issue of #1833.

**Comment by Blargian** [comment]
- [X]  right
- [X]  rightUTF8

**Comment by Blargian** [comment]
Closed by [#62589](https://github.com/ClickHouse/ClickHouse/pull/62589)

**Comment by Blargian** [comment]
Closed by [#62589](https://github.com/ClickHouse/ClickHouse/pull/62589)
