### ISSUE TITLE
Document `roundXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2006]
Create documentation for the `roundXYZ` function. See #1833 for details on how to complete this issue.

- [ ] roundAge
- [ ] roundDown
- [ ] roundDuration
- [ ] roundToExp2

Child issue of #1833.

**Comment by Blargian** [comment]
- [X]  roundAge
- [X]  roundDown
- [X]  roundDuration
- [ ]  roundToExp2
