### ISSUE TITLE
Document `subtractXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2017]
Create documentation for the `subtractXYZ` functions. See #1833 for details on how to complete this issue.

- [ ] subtractDays
- [ ] subtractHours
- [ ] subtractInterval
- [ ] subtractMicroseconds
- [ ] subtractMilliseconds
- [ ] subtractMinutes
- [ ] subtractMonths
- [ ] subtractNanoseconds
- [ ] subtractQuarters
- [ ] subtractSeconds
- [ ] subtractTupleOfIntervals
- [ ] subtractWeeks
- [ ] subtractYears

Child issue of #1833.

**Comment by Blargian** [comment]
- [ ]  subtractDays
- [ ]  subtractHours
- [ ]  subtractInterval
- [ ]  subtractMicroseconds
- [ ]  subtractMilliseconds
- [ ]  subtractMinutes
- [ ]  subtractMonths
- [ ]  subtractNanoseconds
- [ ]  subtractQuarters
- [ ]  subtractSeconds
- [ ]  subtractTupleOfIntervals
- [ ]  subtractWeeks
- [ ]  subtractYears

**Comment by Blargian** [comment]
@johnnymatthews @justindeguzman Here I think we should decide if it will be better to split these functions up individually or have them under one collective entry as they are currently. If we decide to split them then we should also add an issue for the `addXYZ` functions for consistency sake. 
![image](https://github.com/ClickHouse/clickhouse-docs/assets/41984034/23cf29d7-0977-4a8f-89db-82efdea20843)

It maybe makes sense to split them as we have other "`XYZ`" functions which have individual entries such as `toStartOfXYZ`, `toRelativeXYZ` etc:

![image](https://github.com/ClickHouse/clickhouse-docs/assets/41984034/f2060a23-c5db-472c-bfe7-98a2414fecdb)
