### ISSUE TITLE
Document `tupleXYZ` functions.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2030]
Create documentation for the `tupleXYZ` function. See #1833 for details on how to complete this issue.

- [ ] tupleIntDiv
- [ ] tupleIntDivByNumber
- [ ] tupleIntDivOrZero
- [ ] tupleIntDivOrZeroByNumber
- [ ] tupleModulo
- [ ] tupleModuloByNumber

Child issue of #1833.

**Comment by Blargian** [comment]
@johnnymatthews I'll pick this one up.

**Comment by Blargian** [comment]
- [X]  tupleIntDiv
- [X]  tupleIntDivByNumber
- [X]  tupleIntDivOrZero
- [ ]  tupleIntDivOrZeroByNumber
- [ ]  tupleModulo
- [ ]  tupleModuloByNumber
