### ISSUE TITLE
Document `ucase` function.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2031]
Create documentation for the `ucase` function. See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by vdimir** [comment]
Same as `upper`

**Comment by Blargian** [comment]
@johnnymatthews this one can be closed. As mentioned above, it's an alias for [`upper`](https://github.com/ClickHouse/ClickHouse/blob/a691d30177cec5da496226a10726e768ea638032/docs/en/sql-reference/functions/string-functions.md?plain=1#L287-L297).

**Comment by vdimir** [comment]
And this alias is mentioned, so users may find it, that's fine. thanks
