### ISSUE TITLE
Document `version` function.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2037]
Create documentation for the `version` function. See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by nikitamikhaylov** [comment]
This function returns current the version of running ClickHouse server as a string in a form of: 
`major version`.`minor version`.`patch version`.`the number of commits since previous stable release`

Example: 

```
SELECT version()

Query id: 9ac96d6c-613b-4d88-9e2c-2e77c1c2bfe3

┌─version()─┐
│ 24.2.1.1  │
└───────────┘
```

Return type - `String`.
