### ISSUE TITLE
Document `yandexConsistentHash` function.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#2042]
Create documentation for the `yandexConsistentHash` function. See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by alexey-milovidov** [comment]
It is named `kostikConsistentHash`

**Comment by johnnymatthews** [comment]
Interesting. It didn't show up as an alias for `kostikConsistentHash`. If that's the case though, we can close this issue in favour of https://github.com/ClickHouse/clickhouse-docs/issues/1969.
