### ISSUE TITLE
Add Match Systems to adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#2109]
https://matchsystems.com/
https://telegra-ph.translate.goog/Senior-Database-Administrator-11-28?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

**Comment by tylerhannan** [comment]
closed with above commit

@justindeguzman - sorry for pushing to main, misconfig on my new laptop. won't do it again ;(
