### ISSUE TITLE
[Guide] Using ClickHouse for Observability

### ISSUE THREAD

**Issue by justindeguzman** [ClickHouse/clickhouse-docs#2144]
Compile a list of ClickHouse tutorials and best practices for observability use cases based on our experience with LogHouse.

Part of the upcoming Docs series on use case specific pages complimentary to the Blog use case series (cc @kellytoole).

Relevant blog posts:
- https://clickhouse.com/blog/clickhouse-grafana-plugin-4-0
- https://clickhouse.com/blog/the-state-of-sql-based-observability
- https://clickhouse.com/blog/overview-of-highlightio
- https://clickhouse.com/blog/storing-log-data-in-clickhouse-fluent-bit-vector-open-telemetry
- https://clickhouse.com/blog/storing-traces-and-spans-open-telemetry-in-clickhouse
- https://clickhouse.com/blog/how-we-used-clickhouse-to-store-opentelemetry-traces

Action items:
- [x] @justindeguzman will create an outline for “Using ClickHouse for Observability” docs page based on existing blog content (this week)
- [x] @behebot will edit and approve outline
- [x] Once outline is approved, Observability team will write content for that page based on their learnings from LogHouse

cc @kellytoole @tbragin @mikehayesclickhouse

**Comment by kellytoole** [comment]
These might also be useful: 

https://clickhouse.com/blog/nginx-logs-to-clickhouse-fluent-bit
https://clickhouse.com/blog/working-with-time-series-data-and-functions-ClickHouse

cc @gingerwizard

**Comment by gingerwizard** [comment]
Done!
