### ISSUE TITLE
Add AB Tasty to adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#2155]
19:20 AB Tasty - AB Tasty's journey to assess and select Clickhouse Cloud - 20 mins

**Comment by tbragin** [comment]
Which meetup? Link?

**Comment by tylerhannan** [comment]
This will come in a Paris meetup video this week.

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2875
