### ISSUE TITLE
"Invisible" line separator in dark mode

### ISSUE THREAD

**Issue by Blargian** [ClickHouse/clickhouse-docs#2209]
In dark mode the line separator does not show up well against the background, so it looks like there are large empty gaps between the text. (see below comparison between light and dark mode for the same page).

Suggested improvement: styling of the line separator as a lighter color when in dark mode.

![dark_mode_separator](https://github.com/ClickHouse/clickhouse-docs/assets/41984034/7434413d-0bca-47c2-8013-aae9af15e92b)

**Comment by gingerwizard** [comment]
So this is inserted above h2 headers. Looks simple to fix. Addressing.

**Comment by gingerwizard** [comment]
ok lighten stroke color

**Old:**
<img width="1456" alt="image" src="https://github.com/user-attachments/assets/91dcfb3d-e0a7-4c81-9ea3-923c19653f06">


**New:**



<img width="1456" alt="image" src="https://github.com/user-attachments/assets/1953fb78-b02a-4570-8a7a-245e24a68d95">
