### ISSUE TITLE
 Using clickhouse-copier to migrate data, error reported

### ISSUE THREAD

**Issue by SoaringCode** [ClickHouse/clickhouse-docs#2234]
2024.04.22 15:52:55.045500 [ 1746163 ] {} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (59.202.69.93:9000). (NETWORK_ERROR) (version 22.4.5.9 (official build))
2024.04.22 15:52:55.045953 [ 1746163 ] {} <Error> Application: Will retry: Code: 279. DB::NetException: All connection tries failed. Log:

Code: 210. DB::NetException: SSL Exception: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (59.202.69.93:9000). (NETWORK_ERROR) (version 22.4.5.9 (official build))

. (ALL_CONNECTION_TRIES_FAILED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb6fc2fa in /usr/bin/clickhouse
1. PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x16cfc8db in /usr/bin/clickhouse
2. PoolWithFailoverBase<DB::IConnectionPool>::get(unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x16cfa3df in /usr/bin/clickhouse
3. DB::ConnectionPoolWithFailover::get(DB::ConnectionTimeouts const&, DB::Settings const*, bool) @ 0x16cfa299 in /usr/bin/clickhouse
4. DB::ClusterCopier::getCreateTableForPullShard(DB::ConnectionTimeouts const&, DB::TaskShard&) @ 0xb8709af in /usr/bin/clickhouse
5. DB::ClusterCopier::createShardInternalTables(DB::ConnectionTimeouts const&, DB::TaskShard&, bool) @ 0xb87a604 in /usr/bin/clickhouse
6. DB::ClusterCopier::getShardPartitions(DB::ConnectionTimeouts const&, DB::TaskShard&) @ 0xb882b9c in /usr/bin/clickhouse
7. DB::ClusterCopier::discoverShardPartitions(DB::ConnectionTimeouts const&, std::__1::shared_ptr<DB::TaskShard> const&) @ 0xb84eb81 in /usr/bin/clickhouse
8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb7aa77a in /usr/bin/clickhouse
9. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0xb7ac764 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb7a7ba7 in /usr/bin/clickhouse
11. ? @ 0xb7ab5dd in /usr/bin/clickhouse
12. ? @ 0x8fed in /usr/lib64/libpthread-2.28.so
13. clone @ 0xfcbdf in /usr/lib64/libc-2.28.so
 (version 22.4.5.9 (official build))

**Comment by SoaringCode** [comment]
I can connect through the client and perform normal queries

**Comment by alexey-milovidov** [comment]
It isn't supported.
