### ISSUE TITLE
Can't switch from Russian to English

### ISSUE THREAD

**Issue by Guvanchhojamov** [ClickHouse/clickhouse-docs#2238]
1. Open Docs Page: [Docs](https://clickhouse.com/docs)
2. Hover to language selection and select `Russian`
    **After this, you will see the Russian version of the documentation.**
3. Hover to language selection AGAIN and select `English` 
    **Excepted:**
        The _English_ version of the documentation.
     **Actual:**
     Ruh-Roh!   ))))
      
![Screenshot from 2024-04-24 19-29-36](https://github.com/ClickHouse/clickhouse-docs/assets/43471352/f29cc094-26e0-4676-a0b4-77acae35cd8d)

```[tasklist]
### Tasks
```

**Comment by alexey-milovidov** [comment]
Do not switch to Russian.
