### ISSUE TITLE
Add Corsearch to adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#2251]
https://twitter.com/ClickHouseDB/status/1783496616759984131

**Comment by tbragin** [comment]
There is also a meetup talk and soon will be a meetup report, let's add then. https://www.youtube.com/watch?v=BuS8jFL9cvw&list=PL0Z2YDlm0b3iNDUzpY1S3L_iV4nARda_U&index=9

**Comment by tbragin** [comment]
Done.
