### ISSUE TITLE
SELECT documentation doesn't describe WINDOW clause

### ISSUE THREAD

**Issue by lukaseder** [ClickHouse/clickhouse-docs#2294]
The documentation about  the `SELECT` statement doesn't list the `WINDOW` clause, though it's clearly supported and documented elsewhere:

- https://clickhouse.com/docs/en/sql-reference/statements/select
- https://clickhouse.com/docs/en/sql-reference/window-functions

**Comment by gingerwizard** [comment]
Addressed https://github.com/ClickHouse/ClickHouse/pull/73523
