### ISSUE TITLE
`max_download_buffer_size` docs seem to contradict setting description

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/clickhouse-docs#2303]
https://clickhouse.com/docs/en/integrations/s3#read--writes

> max_download_buffer_size. Files will only be downloaded in parallel if their size is greater than the total buffer size combined across all threads

https://clickhouse.com/codebrowser/ClickHouse/src/Core/Settings.h.html#DB::SettingsTraits::Data::max_download_threads

> M(UInt64, max_download_buffer_size, 10\*1024\*1024, "The maximal size of buffer for parallel downloading (e.g. for URL engine) per each thread.", 0)

I assume the later is correct. The former is worded strangely and is confusing.

**Comment by gingerwizard** [comment]
This is now addressed by http://localhost:3000/docs/en/integrations/s3/performance#using-threads-for-reads ill clean up old docs and PR.
