### ISSUE TITLE
Update marketplace docs section of the public docs for ClickHouse Cloud 

### ISSUE THREAD

**Issue by aashishkohli** [ClickHouse/clickhouse-docs#2331]
Currently all our marketplace public docs are listed here: https://clickhouse.com/docs/en/cloud/marketplace

Some of the steps are not clear and do not have the required screenshots etc. to make the process clear to the user. I'm working on google docs to capture steps for each, but I suggest breaking this in to 7 separate pages under the top section CSP Marketplaces:
1. AWS marketplace PAYG signup
2. AWS marketplace private offer signup
3. GCP marketplace PAYG signup
4. GCP marketplace private offer signup
5. Azure marketplace PAYG signup (coming soon)
6. Azure marketplace private offer signup (coming soon)
7. FAQs

@justindeguzman WDYT?

**Comment by justindeguzman** [comment]
This makes sense–then there can be an overview page that links to all of the pages. The FAQs can likely just be in the overview page.

Depending on the length, we can also combine it by cloud provider but we can determine that after the content is written.

**Comment by aashishkohli** [comment]
@justindeguzman - the following are ready for review. I'll share the rest of the docs over the next couple of days.

1. GCP PAYG: https://docs.google.com/document/d/1aDmgVlQARudrFCd-XCxSco2bW3yuz9PjQh2lsJ8c-1A/edit?usp=sharing
2. GCP Commitments: https://docs.google.com/document/d/1TZUCLIPXUrMohOypoDyRXKv_OXEC7j4Kql5VRUV29Rc/edit?usp=sharing
3. AWS PAYG: https://docs.google.com/document/d/1geln229Abd0k5HQkMVCKMkEML1c897_kptyXu3edAL8/edit?usp=sharing
4. Azure PAYG: https://docs.google.com/document/d/1CJrpROCmMV03EwypGGjwbbLlD_9M0huh_pCe0gvy5vc/edit?usp=sharing

What remains:
1. AWS Commitments
2. Azure Commitments
3. FAQs page

We should target these going live Tuesday/Wednesday next week if that is doable to time with the Azure launch. Please LMK if that is an issue.

**Comment by aashishkohli** [comment]
@justindeguzman - here is the AWS commitments doc, also updated above.
https://docs.google.com/document/d/1y0T1-UHMvrZ6gt1MfAqGVERFCCuIgIKn1OJbxZsvybU/edit
