### ISSUE TITLE
Doubt regarding sidebar number

### ISSUE THREAD

**Issue by airforcerosh** [ClickHouse/clickhouse-docs#2354]
Dear Clickhouse Team,

I am uploading the Connect dlt to ClickHouse  doc here : clickhouse-docs/docs/en/integrations/data-ingestion/etl-tools/

It comes with these in the same category : airbyte-and-clickhouse.md
dlt-and-clickhouse.md
nifi-and-clickhouse.md
vector-to-clickhouse.md

I would like to know what I should choose the sidebar_position as? In case you have any specific requirements!

Thank you very much!

Warm Regards,

Roshni Melwani.

**Comment by Blargian** [comment]
@airforcerosh alphabetical order is probably a good one to go with

**Comment by gingerwizard** [comment]
AS @Blargian alphabetical order is preferred.
