### ISSUE TITLE
Update scaling public docs to include horizontal scaling

### ISSUE THREAD

**Issue by aashishkohli** [ClickHouse/clickhouse-docs#2369]
Horizontal scaling is in private preview now. The existing public docs should be replaced by the document linked here which includes details for horizontal scaling.

https://docs.google.com/document/d/1GxI9juHz08sWS7m0pFjRneNNb7xR2EaB025NwJ_Cn3I/edit?usp=sharing

**Comment by justindeguzman** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2409

**Comment by gingerwizard** [comment]
Closed
