### ISSUE TITLE
Page not found on docs

### ISSUE THREAD

**Issue by marckeelingiv** [ClickHouse/clickhouse-docs#2378]
Navigate to: https://clickhouse.com/docs/en/cloud/manage/cmek

See attached for screen shot
![2024-06-05 14_29_02](https://github.com/ClickHouse/clickhouse-docs/assets/32782256/06a794ca-b092-4879-bda4-f3e14d15ac8a)

**Comment by Blargian** [comment]
@marckeelingiv looks to be working again so I will close this issue.
