### ISSUE TITLE
bug: broken link when you click the english button on the docs page

### ISSUE THREAD

**Issue by Ad-Bean** [ClickHouse/clickhouse-docs#2400]
When clicking the English button on the ClickHouse documentation page, the website redirects to a not found page, which appears to be a broken link https://clickhouse.com/docs/en, I guess it should be https://clickhouse.com/docs/en/intro or the index.md is missing?

![image](https://github.com/ClickHouse/clickhouse-docs/assets/54789193/19a17125-e587-4986-8501-dd13ccddb2c9)

**Comment by gingerwizard** [comment]
This got fixed, @Ad-Bean re-open if you still see this.
