### ISSUE TITLE
remove mention of private preview from backups docs

### ISSUE THREAD

**Issue by aashishkohli** [ClickHouse/clickhouse-docs#2418]
The CH Cloud backups docs page has a mention that the feature for "Configurable backups" is currently in private preview. We should remove this note as the feature in GA as of June 20th.

https://clickhouse.com/docs/en/cloud/manage/backups

**Comment by Vero7979** [comment]
Will f/up

**Comment by gingerwizard** [comment]
Removed under https://github.com/ClickHouse/clickhouse-docs/commit/0971e01089eb39dfdc23b1c7e947c1d8e1036786
