### ISSUE TITLE
Add Beekeeper to adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#2487]
![IMG_2605](https://github.com/user-attachments/assets/015d67a5-1194-4045-9aa5-126375d6351b)

**Comment by gingerwizard** [comment]
Can we please get links to meetup, deck, tweet ANYTHING when opening these issues. I need proof before adding to docs.

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2875
