### ISSUE TITLE
Version-specific documentation

### ISSUE THREAD

**Issue by Andersson007** [ClickHouse/clickhouse-docs#2492]
Hello,

The community is developing an [Ansible collection for ClickHouse](https://github.com/ansible-collections/community.clickhouse) and often struggles with the docs having no versions.

There was a similar issue reported in https://github.com/ClickHouse/clickhouse-docs/issues/2125 but i would suggest not mentioning the version (it'd also work and better than nothing) but creating version-specific docs, in other words, be able to choose a version of ClickHouse similar like in PostgreSQL

![Screenshot from 2024-07-16 09-56-31](https://github.com/user-attachments/assets/d1549cae-43a7-41ed-b6d7-5b410bca66da)

It could be based on building docs from corresponding branches matching clickhouse versions.

Would make user life way easier.

**Comment by gingerwizard** [comment]
This is a solution to the same issue as #2125 ill move your comment there and condense.
