### ISSUE TITLE
GitHub doesn't recognize the license type

### ISSUE THREAD

**Issue by blinkov** [ClickHouse/clickhouse-docs#25]
<img width="357" alt="Screenshot 2022-04-04 at 21 30 39" src="https://user-images.githubusercontent.com/623861/161618112-77d0d79c-faa1-43c1-ad08-0428a370ef4c.png">

**Comment by rfraposa** [comment]
@blinkov - do you know why? I'd like to fix this if possible

**Comment by blinkov** [comment]
@rfraposa they use some open-source library to detect a license type from the license file text, and current text didn't match to anything. So you could find a project with the same license type that matched, take a look at their text and see what's the difference. Or figure it out from that library's source code, Google said it's https://github.com/licensee/licensee. Testing should be possible on a fork.

**Comment by rfraposa** [comment]
Our license is "out of scope" for the auto-detection process: see https://github.com/licensee/licensee/issues/343 and  https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license
