### ISSUE TITLE
Blocked by cloudflare only on path  https://clickhouse.com/docs/en/operations/system-tables/error_log

### ISSUE THREAD

**Issue by ddorian** [ClickHouse/clickhouse-docs#2534]
Hi team,

I was viewing https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#error_log, and I clicked to get redirected to https://clickhouse.com/docs/en/operations/system-tables/error_log and I got blocked by the firewall there. 

It's probably the WAF blocking looking at the keywords "system tables error log" in the path. All other paths work ok.

![waf-block](https://github.com/user-attachments/assets/e32c3b49-3bf8-4353-9fc8-99b40e5694ad)

**Comment by juliojimenez** [comment]
Thank you for reporting this!

We have added an exception to prevent this from happening in the future.
