### ISSUE TITLE
MATERIALIZED VIEW with TO syntax (explicit storage table)

### ISSUE THREAD

**Issue by techday84** [ClickHouse/clickhouse-docs#254]
Hi, i want to create a mv from a table with a lot of data. 
I created a explicit storage table with primary keys etc and then insert rows in this table doing a insert into pageviews select xxxx from table_with_a_lot_of_data

My question is, if a create a splicit table with primarys keys, i should to define primary keys again in the mv?

This is my explicit table:

CREATE TABLE IF NOT EXISTS pageviews
(
`a` UInt16,
`b` UInt16,
... more fields ...
)ENGINE = SummingMergeTree()
ORDER BY (a,b,c,d)
PARTITION BY toYYYYMM(fecha) 
PRIMARY KEY (a,b,c,d)
TTL fecha + INTERVAL 4 YEAR

I don't know the correct syntax declaration to the mv,  option a or b? I need to create primary keys again in the mv?

OPTION A:

CREATE MATERIALIZED VIEW name TO pageviews
AS SELECT ... FROM source
GROUP BY a, b, c, d
ORDER BY a, b, c, d

OPTION B:

CREATE MATERIALIZED VIEW name
ENGINE = SummingMergeTree()
PARTITION BY toYYYYMMDD(timestamp)
PRIMARY KEY (a, b, c, d)
TTL timestamp + INTERVAL 3 MONTH
SETTINGS index_granularity = 8192 
AS
SELECT 
  a,
 b,
c,
d,
...
FROM source_table
GROUP BY a, b, c, d
ORDER BY a, b, c, d

thanks in advance

**Comment by rfraposa** [comment]
Your MV uses SummingMergeTree - which is a part of the MergeTree family of table engines - so you have to define a primary key (i.e. the ORDER BY clause).

Your example seems fine, but your primary key for `pageviews` should probably be something more meaningful, like a user ID or a URL. Does your MV have those types of columns? (Sorting by summed values is probably not going to be very useful.)
