### ISSUE TITLE
Create an article with best practices for what system tables to backup

### ISSUE THREAD

**Issue by tsolodov** [ClickHouse/clickhouse-docs#2578]
This ask [came](https://clickhousedb.slack.com/archives/D07HDHYSNKT/p1723740588874349) from community slack channel

<img width="728" alt="image" src="https://github.com/user-attachments/assets/ef685983-f7c8-4133-a38c-b9a6ec221ee8">

**Comment by gingerwizard** [comment]
@mlex hoping your team can shed some insight here. Dump thoughts here and we can craft into a page.

**Comment by mlex** [comment]
All system tables that store historic data (those with `_log` suffix like query_log, part_log, ...) can be backed up and restored just like any other table. It depends on your use case if you want to include those or not. If you rely e.g. on historic data in the query_log for analysis - then it's better to include it in the backup. If you don't need it, don't include it.

System tables related to access management get special treatment from the backup/restore operations. Those tables are: users, roles, row_policies, settings_profiles, quotas. (see this [code](https://github.com/ClickHouse/ClickHouse/blob/master/src/Backups/RestorerFromBackup.cpp#L81-L82)). If those tables are included in a backup, their content will be put in a special `accessXX.txt` file. When those tables are restored, the restore operation will interpret them similar to the `CREATE USER`, `CREATE ROLE`, `GRANT...` statements. That way you can backup and restore the whole access control configuration of a clickhouse cluster.

This works only for "[SQL-driven Access Control and Account Management](https://clickhouse.com/docs/en/operations/access-rights#enabling-access-control)". Users, roles, privileges that are configured in the config files are never included in backups (and can't be restored that way).

**Comment by gingerwizard** [comment]
Added a note to backups thanks @mlex https://github.com/ClickHouse/ClickHouse/pull/73378
