### ISSUE TITLE
Clarify CHC usage / pricing

### ISSUE THREAD

**Issue by aashishkohli** [ClickHouse/clickhouse-docs#2600]
Evaluate places in our docs to clarify CHC (clickhouse cloud credits) usage in our docs and potentially in the MP listings on AWS, GCP, Azure. It looks like some customers are getting confused that paying for CH cloud is more expensive through the marketplace.

context: https://clickhouse-inc.slack.com/archives/C04TML9DVE3/p1724855790944129

Some sections to potentially add this clarification to:
- https://clickhouse.com/docs/en/manage/billing
- https://clickhouse.com/docs/en/cloud/marketplace
- MP listings on all 3 clouds

cc: @justindeguzman , @minodudd , @hans-bakker-clickhouse

**Comment by hans-bakker-clickhouse** [comment]
As a quick fix, can we add a link to the pricing calculator in the pricing section?

**Comment by gingerwizard** [comment]
@aashishkohli please indicate the text you want and the pages. I will PR.

**Comment by aashishkohli** [comment]
I think we should add this question and response to the FAQs section on both the MP and Billing pages linked in the issue description. 

@minodudd - WDYT?

**Is there a different in ClickHouse Cloud pricing whether paying through the cloud provider marketplace or directly to ClickHouse?**
There is no different in pricing between marketplace billing and signing up directly with ClickHouse. In either case your usage of ClickHouse Cloud is tracked in terms of ClickHouse Cloud Credits (CHCs), which are metered in the same way and billed accordingly.

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2886
