### ISSUE TITLE
broken link for "Announcing a New Official ClickHouse Kafka Connector"

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/clickhouse-docs#2634]
On this blog post "[Announcing a New Official ClickHouse Kafka Connector](https://clickhouse.com/blog/kafka-connect-connector-clickhouse-with-exactly-once)", at the "ClickHouse has supported a [number of techniques](https://clickhouse.com/docs/en/integrations/kafka/kafka-choosing-an-approach) to achieve ingestion from Kafka, each with its own respective pros and cons", the shown link is broken

**Comment by Blargian** [comment]
The correct link is: https://clickhouse.com/docs/en/integrations/kafka#choosing-an-approach

**Comment by gingerwizard** [comment]
We'll fix, its not part of docs but thanks for reporting @ramazanpolat

**Comment by mneedham** [comment]
fixed.
