### ISSUE TITLE
Unable to delete a documentation page: "You are trying to create client-side redirections to paths that do not exist"

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/clickhouse-docs#264]
In https://github.com/ClickHouse/ClickHouse/pull/39596/, I tried to move the [Woboq documentation page](https://clickhouse.com/docs/en/development/browse-code) into the [Getting Started](https://clickhouse.com/docs/en/development/developer-instruction) document.

The "DocsCheck" in CI failed with `[ERROR] Error: You are trying to create client-side redirections to paths that do not exist: - /en/development/browse-code`. The only reference to “browse-code” I found was in file “docs/redirects.txt” but even after deleting the corresponding line from this file the error persisted in CI.

I then Installed the [documentation pipeline](https://github.com/ClickHouse/ClickHouse/blob/master/docs/tools/README.md) locally but the error did not reproduce, i.e. the documentation rendered as expected.

So my question would be if you could try to delete files
- docs/en/development/browse-code.md
- docs/ru/development/browse-code.md
- docs/zh/development/browse-code.md

from the ClickHouse repo? I am curious if I just overlooked something or if there is some systematic problem (in the latter case, maybe it's worth [documenting](https://github.com/ClickHouse/ClickHouse/blob/master/docs/tools/README.md) file deletion then?)

**Comment by rschu1ze** [comment]
@DanRoscigno, I guess the redirects need an update. Would you like to have a look? Thanks.

**Comment by DanRoscigno** [comment]
Hi @rschu1ze I fixed the redirects and am now going to remove the files from ClickHouse/ClickHouse.
