### ISSUE TITLE
Invalid link in the example of the materialized view (votes.parquet)

### ISSUE THREAD

**Issue by trevani** [ClickHouse/clickhouse-docs#2641]
Invalid link in the documentation:
https://github.com/ClickHouse/clickhouse-docs/blob/cf1f9dbd30fe0566c0f75943fbe9ee203aaee6f5/docs/en/materialized-view/index.md?plain=1#L90

![Снимок экрана 2024-09-13 130027](https://github.com/user-attachments/assets/77c21bc5-d8af-487b-a71e-b6682a8ed24e)
![Снимок экрана 2024-09-13 130041](https://github.com/user-attachments/assets/26f35838-11ed-4c75-a3e5-2baacef4a58f)

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2870
