### ISSUE TITLE
Documentation of the default value for `async_insert_use_adaptive_busy_timeout` is incorrect

### ISSUE THREAD

**Issue by michaelsmithxyz** [ClickHouse/clickhouse-docs#2649]
The [docs claim](async_insert_use_adaptive_busy_timeout) that this setting is disabled by default, when it is actually enabled by [default](https://github.com/ClickHouse/ClickHouse/pull/58486)

**Comment by alexey-milovidov** [comment]
https://clickhouse.com/docs/en/operations/settings/settings#async_insert_use_adaptive_busy_timeout
