### ISSUE TITLE
four_letter_word_white_list parameter placed in wrong section in doc

### ISSUE THREAD

**Issue by azsane** [ClickHouse/clickhouse-docs#2658]
in docs/en/guides/sre/keeper/index.md ( also for docs/ru doc/zh)

it says

```
Internal coordination settings
Internal coordination settings are located in the <keeper_server>.<coordination_settings> section and have the following parameters:
```

parameters below contains four_letter_word_white_list,but this parameter must be child of <keeper_server>
if you follow the document place four_letter_word_white_list under coordination_settings,
keeper will report UNKNOWN paramter four_letter_word_white_list

**Comment by gingerwizard** [comment]
Confirmed wrong section https://github.com/ClickHouse/ClickHouse/blob/85f86196c4048ed71d0c1277b8ba169197099267/tests/integration/test_keeper_session/configs/keeper_config1.xml#L7

Moving and PR'ing.

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2878
