### ISSUE TITLE
Add Dopple to Adopters from San Francisco Meetup on 9/5

### ISSUE THREAD

**Issue by MarieAsg** [ClickHouse/clickhouse-docs#2664]
https://docs.google.com/presentation/d/1_i7H1EIfEttPKtP9CCAB_4Ajs_Li4N6S/edit?usp=sharing&ouid=107272618557715797204&rtpof=true&sd=true

Thank you!

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2865
