### ISSUE TITLE
Add Harvey to Adopters from San Francisco Meetup on 9/5

### ISSUE THREAD

**Issue by MarieAsg** [ClickHouse/clickhouse-docs#2667]
https://docs.google.com/presentation/d/1WhD-VWW_V53Pe6Zb8qk6L78htkMSempxhVgNrFh7Q6E/edit#slide=id.p

Thank you!

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2865
