### ISSUE TITLE
The PrettyCompactMonoBlock page is missing

### ISSUE THREAD

**Issue by yariks5s** [ClickHouse/clickhouse-docs#2685]
This page appears in the search window:
<img width="581" alt="image" src="https://github.com/user-attachments/assets/22c669f7-3877-4b4b-af65-7309cc206f70">

But it's impossible to visit this page:

<img width="686" alt="image" src="https://github.com/user-attachments/assets/f33cb152-efbf-438a-874c-44191ec85ff1">

**Comment by Blargian** [comment]
@yariks5s link seems to be working again when I search for PrettyCompactMonoBlock. [link](https://clickhouse.com/docs/en/integrations/java/client-v2#clickhouseformat)
