### ISSUE TITLE
Add Attentive to Adopters from NYC Meetup on 9/10

### ISSUE THREAD

**Issue by MarieAsg** [ClickHouse/clickhouse-docs#2691]
[Clickhouse at Attentive - DB Migration.pptx](https://github.com/user-attachments/files/17235049/Clickhouse.at.Attentive.-.DB.Migration.pptx)

Thank you!

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2865
