### ISSUE TITLE
Add Huntress to Adopters from NYC Meetup on 9/10

### ISSUE THREAD

**Issue by MarieAsg** [ClickHouse/clickhouse-docs#2692]
[Copy of Lessons Learned Building The Huntress SIEM With ClickHouse.pptx](https://github.com/user-attachments/files/17235212/Copy.of.Lessons.Learned.Building.The.Huntress.SIEM.With.ClickHouse.pptx)

Thank You!

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/2865
