### ISSUE TITLE
some errors during "yarn start"

### ISSUE THREAD

**Issue by hezh325** [ClickHouse/clickhouse-docs#2703]
The prompt during `yarn start` is “[ERROR] Error: A Docusaurus plugin is missing a 'name
Docusaurus version: 3.5.2
Node version: v20.18.0
![clickhouse-docs](https://github.com/user-attachments/assets/4d6af009-2ca9-4cd0-8e66-840e30279456)
' property.”

**Comment by justindeguzman** [comment]
Did you run `yarn` to install all the packages? You may need to run in Docker also, I have not tested developing locally on Windows.

**Comment by gingerwizard** [comment]
@hezh325 were you able to get this working? any additional help needed?

**Comment by gingerwizard** [comment]
Closing, @hezh325 reopen if you hit this issue (or anyone else please)
