### ISSUE TITLE
Update screenshots in _gather_your_details snippet

### ISSUE THREAD

**Issue by BentsiLeviav** [ClickHouse/clickhouse-docs#2733]
The snippets:
* https://github.com/ClickHouse/clickhouse-docs/blob/9fed0a8bb10f10d3c827847e9d0542228d96a2d0/docs/en/_snippets/_gather_your_details_http.mdx#L11
* https://github.com/ClickHouse/clickhouse-docs/blob/9fed0a8bb10f10d3c827847e9d0542228d96a2d0/docs/en/_snippets/_gather_your_details_http.mdx#L15
* https://github.com/ClickHouse/clickhouse-docs/blob/9fed0a8bb10f10d3c827847e9d0542228d96a2d0/docs/en/_snippets/_gather_your_details_native.md#L11
* https://github.com/ClickHouse/clickhouse-docs/blob/9fed0a8bb10f10d3c827847e9d0542228d96a2d0/docs/en/_snippets/_gather_your_details_native.md#L15

Are outdated in terms of our new Cloud UI.

**Comment by gingerwizard** [comment]
Closed under https://github.com/ClickHouse/clickhouse-docs/pull/2806
