### ISSUE TITLE
Build Clickhouse with DEFLATE_QPL

### ISSUE THREAD

**Issue by Jae0504** [ClickHouse/clickhouse-docs#2739]
Hello, I am trying to build clickhouse with DEFLATE_QPL, but the page is not found. Can I get some help?
https://clickhouse.com/docs/en/development/building_and_benchmarking_deflate_qpl

**Comment by Jae0504** [comment]
Can I use the old version, which supports DEFLATE_QPL, to check the performance?

**Comment by rschu1ze** [comment]
Sure, ClickHouse is open-source, feel free to build or download an older version which still has DEFLATE_QPL.

**Comment by Jae0504** [comment]
Thank you for your help! I can test the performance with qpl. I have some extra questions. 
- Does it use hardware path or software path when I run compression or decompression by codec(DEFLATE_QPL)?
- I saw that if we need to decompress the big data, it will be executed asynchronously. Can I know what will be the size of the data that qpl will be ran as asynchronous mode?

**Comment by rschu1ze** [comment]
Codec DEFLATE_QPL was always experimental (aka. unsupported), the code has been removed in the meantime, and it was contributed and maintained by Intel. Regarding your questions, you are on your own, sorry.
