### ISSUE TITLE
Reference Docs and User Guide on Object Storage

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#274]
In discussion with a user today, we please need to document the S3 object storage. @alexey-milovidov has offered to assist. Elements of the documentation should include at least the following:

* Reference Docs on the object usage
* User Guide for a step-by-step instruction on integration

Thanks

**Comment by DanRoscigno** [comment]
@alexey-milovidov I popped this into the docs from notes that @e-mars provided.  I need to do some cleanup, and then maybe we can go over it next week to see what else is needed. https://clickhouse.com/docs/en/guides/sre/configuring-s3-for-clickhouse-use

**Comment by DanRoscigno** [comment]
Requirements:

- single shard
- two replicas
- replicas in different AWS regions
- zero copy replication disabled

**Comment by DanRoscigno** [comment]
`cconfig.d/mergetree.xml`
```
    <merge_tree>
        <allow_remote_fs_zero_copy_replication>false</allow_remote_fs_zero_copy_replication>
    </merge_tree>
```

**Comment by DanRoscigno** [comment]
published
