### ISSUE TITLE
Add docs for the new types of JOINs

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#283]
[`direct`](https://github.com/ClickHouse/ClickHouse/pull/35363) and [`full_sorting_merge`](https://github.com/ClickHouse/ClickHouse/pull/35796) are new but not documented

**Comment by DanRoscigno** [comment]
closed by https://github.com/ClickHouse/ClickHouse/pull/50484
and https://clickhouse.com/docs/en/operations/settings/settings#settings-join_algorithm
