### ISSUE TITLE
Sidebar change when clicking `deltaLake` link 

### ISSUE THREAD

**Issue by Blargian** [ClickHouse/clickhouse-docs#2905]
On the [sql reference page](https://clickhouse.com/docs/en/sql-reference) when clicking `deltaLake` in the left hand sidebar:

![image](https://github.com/user-attachments/assets/51b50e25-22c1-42d9-8ad2-ab7aea94f4c8)

The sidebar changes, which should not happen:

![image](https://github.com/user-attachments/assets/79d19e76-7063-480e-af7e-309a22fe915f)

The same happens for `Distributed DDL` on the sql reference page:

![image](https://github.com/user-attachments/assets/c11ed9d8-ee7b-4d81-940f-0517cd3e8a63)

**Comment by gingerwizard** [comment]
this was a wider issue. https://github.com/ClickHouse/clickhouse-docs/pull/2912/files closes
