### ISSUE TITLE
Promotheus monitoring reference - broken link

### ISSUE THREAD

**Issue by lio-p** [ClickHouse/clickhouse-docs#2948]
The Promotheus section link on this [page](https://clickhouse.com/docs/en/operations/monitoring) link to a missing part of the documentation.

https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#prometheus

**Comment by Blargian** [comment]
Looks like it was removed by this [commit](https://github.com/ClickHouse/ClickHouse/commit/ffa1371ddebac64b59dac037cc1f03c704c644ce#diff-235ccf8baa886b62296915758c7daba6dadedfc63a3071437d06df9bc68a76edL2125-L2166) during merge of master into the branch... seems accidental as far as I can see. I will add the section back.
