### ISSUE TITLE
This instruction should be somewhere.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#295]
We should have this instruction somewhere:

How to import one table from a self-managed ClickHouse to ClickHouse Cloud:

## On the source database server:

1. Create a temporary user for data import:
```
CREATE USER import_from_cloud IDENTIFIED WITH SHA256_PASSWORD BY 'password-here' SETTINGS readonly = 1;
GRANT SELECT ON db.table TO import_from_cloud;
```

2. Copy the table definition:
```
SHOW CREATE TABLE db.table
```

## On the ClickHouse Cloud:

3. Replace the ENGINE to ReplicatedMergeTree without any parameters and run the CREATE statement:
```
CREATE TABLE db.table ...
```

4. Run the INSERT statement to import the data:
```
INSERT INTO db.table SELECT * FROM remoteSecure('source-hostname', db, table, 'import_from_cloud', 'password-here')
```

Use remote table function if you don't set up TLS or remoteSecure if you have TLS.

## On the source database server:

5. Delete the temporary user after the INSERT is done.
```
DROP USER import_from_cloud
```

**Comment by DanRoscigno** [comment]
thanks, I recently added an example at https://clickhouse.com/docs/en/sql-reference/table-functions/remote/#migration-of-tables-from-one-system-to-another and will update that with your changes above, and also add a page in https://clickhouse.com/docs/en/integrations/migration

**Comment by DanRoscigno** [comment]
done
