### ISSUE TITLE
Something not good with the docs markup in Firefox

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#297]
![Screenshot_20220815_031957](https://user-images.githubusercontent.com/18581488/184667298-4d307bca-2c79-4e04-aa3e-ec41eef2f4fd.png)

**Comment by DanRoscigno** [comment]
I think this is good, @gjones fixed this.  The issue was CSS that is allowed for Chrome but not Firefox.
