### ISSUE TITLE
Substitutions don't work in the docs

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#300]
https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler/
`{% include "examples/sampling_query_profiler_result.txt" %}`
This does not work in the new docs, please remove it from the pages.

**Comment by DanRoscigno** [comment]
syntax is different, I will fix it

**Comment by DanRoscigno** [comment]
That dir (`docs/_includes`) is not made available during the build process.  Can I move the dir under `docs/en/` ?  Then I can include the file like this:
```
import CodeBlock from '@theme/CodeBlock';
import ProfilerResult from '!!raw-loader!/docs/_includes/examples/sampling_query_profiler_result.txt';

<CodeBlock>{ProfilerResult}</CodeBlock>
```

**Comment by blinkov** [comment]
I think originally it was introduced to avoid copy-pasting between languages, so it kinda ruins the purpose.

**Comment by DanRoscigno** [comment]
> I think originally it was introduced to avoid copy-pasting between languages, so it kinda ruins the purpose.

All of the files in there are in English, if there were Russian or Chinese files in there I would agree.  Maybe I don't understand.

**Comment by alexey-milovidov** [comment]
I've removed it.
