### ISSUE TITLE
Enum settings documentation issues

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-docs#316]
While working on the Clickhouse NodeJS client, I noticed some discrepancy between docs enum values and what the ClickHouse server actually allows as input

* `ASOF` is not a valid value here on 22.6
https://clickhouse.com/docs/en/operations/settings/settings/#settings-join_default_strictness

```
Unexpected value of JoinStrictness: 'ASOF'. Must be one of ['ANY', 'ALL', '']. 
```

* `direct` / `auto` / `full_sorting_merge` cannot be used for https://clickhouse.com/docs/en/operations/settings/settings/#settings-join_algorithm

```
Unexpected value of JoinAlgorithm: 'default'. Must be one of ['prefer_partial_merge', 'hash', 'parallel_hash', 'partial_merge', 'auto']. 
```

* `best_effort_us` is missing
https://clickhouse.com/docs/en/operations/settings/settings/#date_time_input_format

* `None` is missing from
https://clickhouse.com/docs/en/operations/settings/settings/#format_custom_escaping_rule

* https://clickhouse.com/docs/en/operations/settings/settings/#settings-log-queries-min-type is a bit confusing, one can think that it's possible to specify a number instead of a string value (i.e. `2` instead of `QUERY_FINISH`)

There are several settings keys I noticed missing from the doc
```
send_logs_level
mysql_datatypes_support_level
default_table_engine
```

if any of these findings are valid I'd be happy to help to resolve them.

CC @mshustov

**Comment by DanRoscigno** [comment]
Thanks @slvrtrn , I appreciate it.  For `ASOF`, is it valid for 22.8? Maybe it was added after 22.6?  For the rest of them, I don't have any ideas.  If you need any help with formatting doc updates I am happy to help, I have not written a style / example guide yet for docs.

**Comment by slvrtrn** [comment]
@DanRoscigno it's the same on 22.8.1

```
Error: Unexpected value of JoinStrictness: 'ASOF'. Must be one of ['ANY', 'ALL', ''].
```

**Comment by slvrtrn** [comment]
@DanRoscigno 

> If you need any help with formatting doc updates 

thanks! I'd be happy to help but I need to understand whether the rest of the findings are valid (i.e. non-existing values should be indeed removed from the docs).

**Comment by DanRoscigno** [comment]
> @DanRoscigno
> 
> > If you need any help with formatting doc updates
> 
> thanks! I'd be happy to help but I need to understand whether the rest of the findings are valid (i.e. if non-existing values should be indeed removed from the docs).

I think some detective work is needed to find out, for example, when `ASOF` was removed from the list of options for JoinStrictness in the code.

**Comment by johnnymatthews** [comment]
I'm gonna close this for now. If this is still a problem, please re-open.
