### ISSUE TITLE
Hit a 404 with the BI/UI connect page

### ISSUE THREAD

**Issue by dipankarqlik** [ClickHouse/clickhouse-docs#325]
Hi, I was trying to learn more about connecting ClickHouse with BI tools and hit a 404 with this page : https://clickhouse.com/docs/en/connect-a-ui/

**Comment by DanRoscigno** [comment]
Hi @dipankarqlik is it working now?  It is working fine for me.

**Comment by rfraposa** [comment]
This page was redirected...so it's a caching issue. A refresh of the page should work.
