### ISSUE TITLE
on main page, link to header documents goes to reference, old docs

### ISSUE THREAD

**Issue by e-mars** [ClickHouse/clickhouse-docs#35]
selecting documents in header at base `clickhouse.com` directs to `https://clickhouse.com/docs/en/` instead of new docs page.
Not sure if this is intentional by design or if the link is supposed to go to new docs landing page `https://clickhouse.com/docs/intro`, etc.
![Screen Shot 2022-04-05 at 12 06 08 PM](https://user-images.githubusercontent.com/18219420/161822015-aa258716-d270-42a5-9b60-e4e346a90b70.png)

**Comment by rfraposa** [comment]
This is fixed now
