### ISSUE TITLE
Update the "ClickHouse Upgrade" page in docs

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#364]
We have some good notes from Alexey in the Technical AMA call, and also:

> we also should add more recommendations about upgrade process, like: Always upgrade when new minor version is released; Don't do rolling upgrade if difference between versions is more than 1 year (upgrade with downtime or through an intermediate version then)

**Comment by DanRoscigno** [comment]
closed by https://github.com/ClickHouse/ClickHouse/commit/1027ce8d77c0a329d6b3ce8a4e435d15b66827ab
