### ISSUE TITLE
Additional Documentation for HDFS settings

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#371]
We have a user who was trying to configure the HDFS Engine and was seeing a problem where writes were using the HDFS table function rather than writing to the HDFS Endpoint.

The key fix was to update the table SETTINGS to use the HDFS Endpoint, so need to be very clear that the endpoint needs to be defined for the table. Another recommendation that should be very clear to use large batches for writes in order to reduce number of written files.

The relevant page in the Docs is here:
https://clickhouse.com/docs/en/operations/storing-data/#configuring-hdfs

cc: @e-mars

**Comment by e-mars** [comment]
thanks @thomoco . 
Docs can prob add a note to ensure that the customer knows that you have to specify the policy.
However, near future might be best to create User Guides as we have built for S3 where we can at least do a simplified/reproducible example for HDFS table engine and using HDFS as storage.  I'll work on those.
Both issues encountered by the user.

**Comment by johnnymatthews** [comment]
> However, near future might be best to create User Guides as we have built for S3 where we can at least do a simplified/reproducible example for HDFS table engine and using HDFS as storage. I'll work on those.

@e-mars were you able to create the referenced user-guides? No worries if not, just trying to figure out how much work is left for this issue.

**Comment by e-mars** [comment]
hi @johnnymatthews . sorry no, it was a rare ask and was down in priority. i no longer have the labs used to reproduce the config and issues.
