### ISSUE TITLE
`allow_experimental_geo_types` warning

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-docs#374]
[Geo](https://clickhouse.com/docs/en/sql-reference/data-types/geo) has a warning about required `allow_experimental_geo_types` setting. 
However, there are no issues working with Geo types without this setting with a local docker instance (22.8).

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/41481
