### ISSUE TITLE
UI visualization - Page Not Found

### ISSUE THREAD

**Issue by maxim-swanlake** [ClickHouse/clickhouse-docs#376]
On this page: https://clickhouse.com/docs/en/quick-start  

When I click on a link "user guides for connecting a UI to ClickHouse"  
"[user guides for connecting a UI to ClickHouse](https://clickhouse.com/docs/en/connect-a-ui/)"

I get "Page Not Found" error.

**Comment by DanRoscigno** [comment]
Thanks, fixed!
