### ISSUE TITLE
Header on the 404 page is barely readable in dark mode

### ISSUE THREAD

**Issue by blinkov** [ClickHouse/clickhouse-docs#409]
![Screenshot 2022-10-01 at 16 57 05](https://user-images.githubusercontent.com/623861/193415479-4170a383-5e01-44bc-a861-79578489d023.png)

**Comment by DanRoscigno** [comment]
PR does not seem to have fixed it.

**Comment by DanRoscigno** [comment]
closed by https://github.com/ClickHouse/clickhouse-docs-content/pull/46
