### ISSUE TITLE
Move the example datasets up higher in the side navigation

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#44]
And also we should reorder to put the most interesting datasets first. (Let's put UK Property Price Paid first)

**Comment by DanRoscigno** [comment]
Getting there.  I have the example datasets up top and the UK property example at the top.  Next I need to remove the examples from the Reference > Getting Started section.
![image](https://user-images.githubusercontent.com/25182304/168122607-57969839-f654-4c1f-a224-fd84bc5c30e6.png)

**Comment by rfraposa** [comment]
Let's put the NYC taxi data second on the list
