### ISSUE TITLE
Cloud, UX: Connection URL is really hard to find on admin page

### ISSUE THREAD

**Issue by ilyazz** [ClickHouse/clickhouse-docs#441]
Ok, here's my story. I signed up for the beta, created a service, and tried to write a simple Go application.
It took me some time to find the connection URL. (`https://xxxxxxx.us-west-2.aws.clickhouse.cloud:8443`)
It's not a secret data, and it's probably the most important attribute of the service, so I'd expect it on the main service page. 
But it looks like the shortest path to get it is `Actions/Load Data` menu and there get it from the curl example.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/11165895/194166319-27384df9-6685-459f-879d-3df952c66a7f.png">

PS: not sure this is the right repo to report cloud UX issues

**Comment by DanRoscigno** [comment]
Thanks @ilyazz , I will get your issues to the right people.  I don't do Go myself, so I am not of much help, but I am assigning the right people to get things resolved.  I am adding the instructions for grabbing those connection details to all of the appropriate pages, and will hit the go pages next, and will pass the feedback on to the UX folks.  We appreciate your feedback!

**Comment by ilyazz** [comment]
I played a bit with language clients. It looks like different server side ports are used by different clients. 
With Go I was able to connect to 9440, and python's `clickhouse_connect` package uses 8443.

Would be really nice to have all active server ports specified and documented.

**Comment by DanRoscigno** [comment]
There are two ports, one for HTTPS and one for native TCP.  Some of the language clients use HTTPS and some use native TCP.  The same place where you found the connection details (the screenshot up in the original comment) has links to the docs for the interfaces.  Each client should specify the port(s) that it uses (some can use both HTTPS and native TCP).  As I add the details to the docs for the cloud connection details those will get checked, and I have an issue open with the UX folks about having that info in the Cloud console where you first see the instructions  in Cloud.

**Comment by DanRoscigno** [comment]
![image](https://user-images.githubusercontent.com/25182304/221625326-02e0adb3-541c-4c10-bd1a-0d17bdaf3470.png)

fixed
