### ISSUE TITLE
Cloud: golang integration example.

### ISSUE THREAD

**Issue by ilyazz** [ClickHouse/clickhouse-docs#442]
Cloud/Service/Action/Load Data/Go

The code example could be better:
1. The example is displayed in the context of the particular service, so it would be great to use the actual `Addr` instead of `127.0.0.1`
2. The code itself is pretty terrible. It fills many of the fields of `clickhouse.Options` object, including rarely used such as `Debugf`. It uses undeclared variable `dialCount`. What I expect, is a clear and simple way how to connect to my DB, and for this only `TLS`, `Addr` and `Auth` have to be set. The rest I can get from the client golang doc (would be nice to have a link to).

<img width="832" alt="image" src="https://user-images.githubusercontent.com/11165895/194168934-cebffc19-f568-49dd-92e7-e342e3512f6d.png">

**Update**:
This code example is not working with CH Cloud at all, actually.
It tries to establish an unsecured connection with a server, and returns an error ` 10.0.0.23:64539->35.85.205.122:9440: read: connection reset by peer`

To make it work the `Options` object has to have TLS configuration:
```
 c, err := clickhouse.Open(&clickhouse.Options{                             
                Addr: []string{"kl5nodobpi.us-west-2.aws.clickhouse.cloud:9440"},
                Auth: clickhouse.Auth{                                             
                        Database: "default",                                       
                        Username: "default",                                       
                        Password: "xxx",                                  
                },                                                                 
                TLS: &tls.Config{},      // !                                      
        }) 
```

**Comment by gingerwizard** [comment]
Agreed this example appears to have been taken from a rather complex example. I'll prepare a working cloud example. Using credentials for the cluster itself @Ryado might now if this possible.

**Comment by mshustov** [comment]
updated
