### ISSUE TITLE
Small adjustment about INSERT Atomicity

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/clickhouse-docs#444]
Insert isn't atomic if `input_format_parallel_parsing` setting is enabled (and it's enabled by default)

https://github.com/ClickHouse/ClickHouse/issues/23303

https://clickhouse.com/docs/en/guides/developer/transactional

**Comment by DanRoscigno** [comment]
@alexey-milovidov , can you comment?

**Comment by UnamedRus** [comment]
@DanRoscigno 

Repeated test on new version and result is exactly the same.

```
❯ clickhouse-client -mn --query "CREATE TABLE test_atomic_insert (a UInt32, b UInt32, c UInt32, d UInt32, e String)ENGINE=MergeTree() ORDER BY a"
❯ clickhouse-client -mn --query "SELECT number as a, number as b,number as c, number as d, 'some_longString' as e FROM numbers(999999) FORMAT JSONEachRow" | clickhouse-client --query "INSERT INTO test_atomic_insert SELECT * FROM input('a UInt32, b UInt32, c UInt32, d UInt32, e String') FORMAT JSONEachRow" --input_format_parallel_parsing=1
^CError on processing query: Code: 75. DB::ErrnoException: Cannot write to file (fd = 1), errno: 32, strerror: Broken pipe. (CANNOT_WRITE_TO_FILE_DESCRIPTOR) (version 22.10.1.1435)
(query: SELECT number as a, number as b,number as c, number as d, 'some_longString' as e FROM numbers(999999) FORMAT JSONEachRow)
❯ clickhouse-client -mn --query "SELECT count() FROM test_atomic_insert; TRUNCATE TABLE test_atomic_insert;"
143819
❯ clickhouse-client -mn --query "SELECT version()"
22.10.1.1435
``

**Comment by Avogar** [comment]
@DanRoscigno I can explain it to you.

When we don't use parallel parsing, during data insert in some row-based format (like JSONEachRow) we parse data row by row and construct a block from them. The maximum size of one block during insert is controlled by setting `max_insert_block_size` with default value `1048449`. So if the number of rows in input data is less then `max_insert_block_size`, we will construct only one block of data and this insert will be atomic. It means that if we cancel insert query somewhere in the middle, no data will be insert from this signle block.
When we use parallel parsing, we divide the data into segments and parse them concurrently. Each segment can contain no more than `max_insert_block_size` rows. But also we have setting `min_chunk_bytes_for_parallel_parsing` that controls the minimum size of segment in bytes, so we stop constructing segment when we reached `max_insert_block_size` rows or `min_chunk_bytes_for_parallel_parsing` bytes. So in this case if we have less than `max_insert_block_size` rows but they are big we can reach `min_chunk_bytes_for_parallel_parsing` and devide data into several segments -> we will get more than one block of data and insert will not be atomic
