### ISSUE TITLE
Add a dark mode option

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#45]
We should consider modifying the CSS so that we can enable dark mode but still keep the CH look-and-feel. Who knows, it might look OK out-of-the-box! But I suspect we will need some design effort.

**Comment by tom-clickhouse** [comment]
For our excalidraw diagrams there is a working solution

- [here](https://stackoverflow.com/questions/64425555/is-it-possible-to-detect-if-docusaurus-is-in-light-or-dark-mode) is an example of an conditional image selection based on if the page is shown in dark or light mode

- and in excalidraw it is super easy to get a dark mode version of all diagrams as there is a magic toggle for switching between light and dark mode:
<img width="858" alt="Screenshot 2022-06-02 at 18 29 23" src="https://user-images.githubusercontent.com/97666923/171679323-7bff1f06-fbf2-435a-84bb-285fa9f132bd.png">

<img width="807" alt="Screenshot 2022-06-02 at 18 29 29" src="https://user-images.githubusercontent.com/97666923/171679367-e9a0e7f5-db4f-49e0-ab8f-90a921b4233f.png">

**Comment by DanRoscigno** [comment]
complete.
