### ISSUE TITLE
Links to images in Tableau tutorial are broken

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-docs#453]
Images on https://clickhouse.com/docs/en/connect-a-ui/tableau-and-clickhouse/ page cannot be found

**Comment by DanRoscigno** [comment]
@rfraposa Do you know where the images for https://clickhouse.com/learn/lessons/connect-tableau-to-clickhouse/images/connecttoserver.png etc. are?

**Comment by rfraposa** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/457
