### ISSUE TITLE
Use the same style for all language client docs

### ISSUE THREAD

**Issue by ilyazz** [ClickHouse/clickhouse-docs#461]
https://clickhouse.com/docs/en/integrations/language-clients

There are four language clients documented. Each uses its own styling. Some have ToC, some don't. Prerequisites are described in `Environment requirements` section for NodeJS and in `Prerequisites` for Java. And so on.

It would be nice to unify it and use the same styling for all sections.

**Comment by DanRoscigno** [comment]
working on in integrations repo.
