### ISSUE TITLE
non-obvious Next/Previous links in language client docs

### ISSUE THREAD

**Issue by ilyazz** [ClickHouse/clickhouse-docs#463]
Just a nitpick

Every doc page has previous/next links on bottom.
For a language client doc such links can refer to other language section, which is a bit confusing.

For example:
https://clickhouse.com/docs/en/integrations/python
![image](https://user-images.githubusercontent.com/11165895/194638973-a9e62ace-6e53-4d77-b37e-84eeff9f2fc0.png)

For the python client the "Performance Tips" link refers to the Go client performance tips

**Comment by DanRoscigno** [comment]
closing, as this is addressed in the new CSS being rolled out soon.  Please re-open after the redesigned docs come out if it still needs to be addressed.
