### ISSUE TITLE
Need HowTo projection content

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/clickhouse-docs#470]
https://presentations.clickhouse.com/percona2021/projections.pdf
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#projections
https://clickhouse.com/docs/en/sql-reference/statements/alter/projection/
https://clickhouse.com/docs/en/getting-started/example-datasets/uk-price-paid#speedup-with-projections

**Comment by johnnymatthews** [comment]
Closing.
