### ISSUE TITLE
Broken documentation link for AggregatingMergeTree

### ISSUE THREAD

**Issue by sheridanvk** [ClickHouse/clickhouse-docs#491]
Reporting broken docs link as requested! https://clickhouse.com/docs/en/table_engines/aggregatingmergetree.html

**Comment by DanRoscigno** [comment]
Hi @sheridanvk I think this is the page you want:
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/aggregatingmergetree/

Do you remember where you found the broken link?

Thanks,
Dan

**Comment by DanRoscigno** [comment]
fixed.
