### ISSUE TITLE
add file extension aliases

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/clickhouse-docs#520]
match extension and format by name case insensitive, for example, data.tsv -> TSV, data.tSv -> TSV, data.TSVWithNames -> TSVWithNames, data.parquet -> Parquet. Also ClickHouse supports some well known aliases: data.pb -> Protobuf, data.jsonl, data.ndjson -> JSONEachRow, etc

cc: @Avogar

**Comment by Avogar** [comment]
Mostly we match extansion and format just by format name case insensitive.
Aliases we use:
.bin -> RowBinary
.capnp -> CapnProto
.pb -> Protobuf
.jsonl, .ndjson -> JSONEachRow
messagepack -> MsgPack

If you think we can add more aliases to some formats, let me know, I will add them in our code

**Comment by DanRoscigno** [comment]
handled in code
