### ISSUE TITLE
Add cross reference for char() and ascii() functions. 

### ISSUE THREAD

**Issue by qoega** [ClickHouse/clickhouse-docs#562]
I was looking for `unchar` function and there is `ascii` that works as supposed.
```
SELECT number, char(number) as _char, ascii(_char) as _ascii from numbers(256)
```

**Comment by DanRoscigno** [comment]
I don't understand what `unchar` is

**Comment by DanRoscigno** [comment]
We have no unchar() function, and it is not an alias to ascii()
