### ISSUE TITLE
Refactor the S3 table engine integration guide.

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#566]
The feedback from a user on the S3 docs page:
https://clickhouse.com/docs/en/engines/table-engines/integrations/s3/

The user felt that what was most important on this page was the Endpoint Definition at the very end of the page [setting up the auth correctly](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3/#endpoint-settings) and then the first part of the page on [creating an S3 Table](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3/#creating-a-table).

Would we perhaps want to restructure this page to sequence with the Endpoint Definition first and then Create Table?

**Comment by gingerwizard** [comment]
We have compromised. The example is moved to the top but unless there is further evidence the settings are advanced and belong further down.
