### ISSUE TITLE
Add The Guild, MetricFire, DoubleCloud, RELEX, Rokt, Azureprice, Kyligence, NetMeta, Tiktok to adopters.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#620]
https://the-guild.dev/blog/graphql-hive-and-clickhouse
https://www.metricfire.com/blog/using-clickhouse-with-metricfire/?utm_source=xenon&utm_medium=twitter&utm_campaign=social

**Comment by alexey-milovidov** [comment]
https://blog.devgenius.io/how-i-migrate-to-clickhouse-and-speedup-my-backend-7x-and-decrease-cost-by-6x-part-1-2553251a9059

**Comment by alexey-milovidov** [comment]
RELEX: presentations.clickhouse.com/meetup65/CRUDy%20OLAP.pdf

**Comment by alexey-milovidov** [comment]
Kyligence: https://kyligence.io/all-inclusive-olap/

**Comment by alexey-milovidov** [comment]
NetMeta: https://twitter.com/leolukde/status/1605643470239977475

**Comment by alexey-milovidov** [comment]
Tiktok will be a duplicate record to Bytedance, but we still need to add it.

**Comment by DanRoscigno** [comment]
I added all but Tiktok, I don't see a ref for that one.

**Comment by alexey-milovidov** [comment]
Ok. I've found multiple job postings, but it does not explicitly say about ClickHouse usage.
