### ISSUE TITLE
Add additional details to Kafka integration for streaming recommendations

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#623]
As discussed today, let's please add a new User Guide on end-to-end Kafka streaming setup.

We have the following existing docs:
* Kafka engine: https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka/
* Kafka integration: https://clickhouse.com/docs/en/integrations/kafka/kafka-table-engine/

What I'm requesting here would be a more user-focused step-by-step User Guide that would walk through setup and optimization for Kafka and Kafka Connect to ClickHouse and ClickHouse Cloud. This would include topics such as:

* Installation
* Configuration
* Security
* Performance
* Bulk insert recommendations, async_insert, and kafka_max_block_size
* Focus on streaming use cases, where the data stream may be continuous, and taking into account either smaller or larger streams
* Single or Multiple topics

Looking at the second page I mentioned https://clickhouse.com/docs/en/integrations/kafka/kafka-table-engine/ , we may just need to add some additional details for how to optimize for various topics and stream volumes.

cc: @CamiloSierraH @Ryado

**Comment by gingerwizard** [comment]
@thomoco this is very old, we have decent docs on Kakfa now e.g. https://clickhouse.com/docs/en/integrations/kafka/clickhouse-kafka-connect-sink#tuning-performance closing but feel free to reopen if we need more detail.
