### ISSUE TITLE
JSON: Update examples

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/clickhouse-docs#659]
From @Avogar :

When using JSONAsObject:
add SETTINGS allow_experimental_object_type=1 and after that add same queries with SETTINGS input_format_json_read_objects_as_strings=1 to show that we can load such dataset without using JSON object type.

**Comment by DanRoscigno** [comment]
check current docs, this shows that experimental object is not always needed.  This may have been completed during update.

**Comment by johnnymatthews** [comment]
This seems to be addressed in https://clickhouse.com/docs/en/interfaces/schema-inference#input_format_json_read_objects_as_strings. Closing.
