### ISSUE TITLE
Problem at this old quick start URL

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#66]
This URL is not displaying correctly for me:
https://clickhouse.com/docs/quick-start/

I think it should probably redirect to:
https://clickhouse.com/docs/en/quick-start/

However, this URL is still found in Google Search for "clickhouse quick start":
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8918693/166083918-66e8ded5-beec-4f8e-b63d-0333c1421e40.png">

Result upon clicking on it - land on an odd-looking page
<img width="962" alt="image" src="https://user-images.githubusercontent.com/8918693/166083960-48e953c2-71f2-41e5-894d-c5c22af69067.png">

**Comment by rfraposa** [comment]
Where did you get that URL? Was it a bookmark?

**Comment by rfraposa** [comment]
OK - I better add a redirect then. Thanks for finding this!

**Comment by rfraposa** [comment]
Fixed
