### ISSUE TITLE
Replace ZooKeeper to ClickHouse Keeper in docs and tutorials.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#67]
Keep ZooKeeper as obsolete option.

**Comment by DanRoscigno** [comment]
@alesapin @antonio2368 can you please tell me if all of the `test_keeper*` integration tests are for both ClickHouse Keeper and ZooKeeper, or just one of them?  This will help me know if the SSL settings should be documented for ClickHouse Keeper.
https://github.com/ClickHouse/ClickHouse/tree/master/tests/integration/test_keeper_secure_client

I am looking at these docs at the moment: https://github.com/ClickHouse/ClickHouse/blob/8f01fe9c496386013837da017fb8b8e7dd850651/docs/en/operations/ssl-zookeeper.md

**Comment by DanRoscigno** [comment]
same question for server settings, when it says ZooKeeper in the docs can I say that `default_replica_path` and the other settings for replication are applicable to both ClickHouse Keeper and ZooKeeper?
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#default_replica_path

**Comment by DanRoscigno** [comment]
also, `system.zookeeper_log`, I do not see this table, although I do have system.zookeeper`.  I cannot find a place to configure that table, is there a specific action that I need to take ?

**Comment by antonio2368** [comment]
@DanRoscigno yes all the `test_keeper*` integration tests test different aspects of ClickHouse Keeper.
