### ISSUE TITLE
FAQ additions

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#7]
- [x] How to choose a primary key?
- [ ] How to add a column in ClickHouse?
- [x] Too many parts
- [ ] How to filter ClickHouse table by an array column contents?
- [ ] How to insert all rows from one table to another of identical structure?
- [x] How to kill a process (query) in ClickHouse?
- [ ] How to implement pivot (like in pandas)?
- [ ] How to remove the default ClickHouse user through users.d?
- [x] Importing MySQL dump to ClickHouse
- [ ] Window function workarounds (row_number, lag/lead, running diff/sum/average)

**Comment by johnnymatthews** [comment]
Closing in favour of individual issues referenced above,.
