### ISSUE TITLE
Convert system tables from a list-view to a table-view.

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/clickhouse-docs#706]
A minor visual annoyance I noticed is that the documentation of ClickHouse's system tables (= everything below [this document](https://clickhouse.com/docs/en/operations/system-tables/)) is laid out as enumeration. A table layout would be slightly easier to read.

For example, compare
- https://clickhouse.com/docs/en/operations/system-tables/query_log/

vs.

- https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20ad197a75191014ad6f935d3c9200ca.html?version=2.0.03
- https://www.ibm.com/docs/en/db2-for-zos/11?topic=tables-locations
- https://learn.microsoft.com/en-us/sql/relational-databases/system-tables/msagent-profiles-transact-sql?view=sql-server-ver16

**Comment by gingerwizard** [comment]
Ideally we'd auto-generate the table.

**Comment by rschu1ze** [comment]
I added a note to #2730. Let's do this task in the scope of #2730. Closing.
