### ISSUE TITLE
Add Usermaven to Adopters

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#716]
https://news.ycombinator.com/item?id=34391374
also scan the whole thread.

Update the Wikipedia page: https://en.wikipedia.org/wiki/List_of_web_analytics_software

**Comment by tylerhannan** [comment]
Assigning to me as I'm making other, similar, updates.

**Comment by tylerhannan** [comment]
To the link above I have added 

Posthog and Plausible into the free/floss category.

**Comment by tylerhannan** [comment]
closed by #794
