### ISSUE TITLE
Add ServiceNow, Disney, CHEQ, Rokt

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#756]
https://www.youtube.com/playlist?list=PL0Z2YDlm0b3iNDUzpY1S3L_iV4nARda_U

**Comment by tylerhannan** [comment]
Multiples added in this commit

https://github.com/ClickHouse/clickhouse-docs/pull/794/commits/78ee3b9a6d5c3ecf2a9a306deacd2ef3d80a6b60

**Comment by tylerhannan** [comment]
closed by #794
