### ISSUE TITLE
Document the `clickhouse-diagnostics` executable.

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#768]
Let's please add the steps for locating and running clickhouse-diagnostics to the Docs. This documentation in GitHub should mostly be sufficient:

https://github.com/ClickHouse/ClickHouse/tree/master/programs/diagnostics

However, let's please be sure to add additional details that include the following:

* Dependencies to run
* Location of the binary within file system
* Package included in distribution clickhouse-common-static-*

Thanks - cc: @gingerwizard @DanRoscigno

**Comment by gingerwizard** [comment]
This got moved out of clickhouse to its own repo, where its documented https://github.com/ClickHouse/clickhouse-diagnostics
