### ISSUE TITLE
Add upgrade instructions for curl install

### ISSUE THREAD

**Issue by justindeguzman** [ClickHouse/clickhouse-docs#802]
The current docs don't show an example of how you can upgrade ClickHouse installed via `curl`

https://clickhouse.com/docs/en/operations/update/

**Comment by rfraposa** [comment]
I think the `curl` command is for getting started. Any sort of production installs should use the appropriate install method...and should therefore upgrade accordingly. I wouldn't want users to think we were somehow promoting this curl option too seriously. (Not to downplay it at all! I love the curl command.)

How do you "upgrade" with curl? Don't you just run it again?

**Comment by justindeguzman** [comment]
>How do you "upgrade" with curl? Don't you just run it again?

That's what was confusing me–I tried running curl again, and it just installed a separate binary. I think if we're pushing curl as the primary (or at least initial) installation method there needs to be an upgrade path.

**Comment by alexey-milovidov** [comment]
Step 1: Do `./clickhouse install` on every replica.
Step 2: Restart replicas one by one.

**Comment by alexey-milovidov** [comment]
I'd still recommend deb/rpm/tgz release packages for production, but installing the latest version by curl is totally ok for "fast-moving" companies.

**Comment by justindeguzman** [comment]
Ok specifically for Mac, `./clickhouse install` results in an error. Should we just add to the doc that if you install using `curl` and Mac, you should remove and re-install:

```
rm -rf ./clickhouse
curl https://clickhouse.com | sh
```

Or would this break things?

In general, I think Mac users would just be a lot more comfortable with `brew` since that's what they are comfortable using locally when installing/upgrading/removing.

**Comment by alexey-milovidov** [comment]
Downloading the new version and then renaming the file is safer.

**Comment by rfraposa** [comment]
Yes - remove the binary and redownload. I do it often and it works fine on my Mac. But for the quick start, I am not going to show users how to run `clickhouse install`. 1) It doesn't work on a Mac, and 2) it requires `sudo` on Linux. It's an unnecessary step for someone who is just trying to see what ClickHouse does.

Like I said, the curl command is great - but I just don't see how we promote this as a serious install method. I'm happy to add a comment somewhere about deleting and re-downloading the file, but it will be subtle. 

`brew` is great, but I don't know how to create a tap.
