### ISSUE TITLE
Add the following companies into the Adopters list.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#805]
[Groww](https://stackshare.io/groww/groww)
[Avito](https://stackshare.io/avito/avito)
[useinsider](https://stackshare.io/useinsider/useinsider)
[bigin](https://stackshare.io/big-insight/bigin)
[AppsFlyer](https://stackshare.io/appsflyer/appsflyer)
[domclick](https://stackshare.io/dom_click/domclick)
[Content Square](https://stackshare.io/contentsquare/content-square)
[Mux](https://stackshare.io/mux/mux)
[seo.do](https://stackshare.io/seo-do/seo-do)
[AdCombo](https://stackshare.io/adcombo/adcombo)
[SEMrush](https://stackshare.io/semrush/semrush)
[5G Systems](https://stackshare.io/5g-systems/5g-systems)
[Trell](https://stackshare.io/trell/trell)
[PC Pulse](https://stackshare.io/pc-pulse/pc-pulse)
[Kartaca](https://stackshare.io/kartaca/kartaca)
[Cimri](https://stackshare.io/cimri/cimri)
[Weave](https://stackshare.io/getweave/weave)
[HeadHunter](https://stackshare.io/headhunter/headhunter)
[Panelbear](https://stackshare.io/panelbearhq/panelbear)
[Sematext Cloud](https://stackshare.io/sematext/sematext-cloud)
[DevTeam](https://stackshare.io/retail-rocket/devteam)
[Oktopost](https://stackshare.io/oktopost/oktopost)
[Kameleoon](https://stackshare.io/kameleoon/kameleoon)
[DevOps](https://stackshare.io/singular-group/devops)
[omosuite](https://stackshare.io/omosuite/omosuite)
[Findify](https://stackshare.io/findify/findify)
[Xenoss](https://stackshare.io/xenoss/xenoss)
[Knotch](https://stackshare.io/knotch/knotch)
[Gitential](https://stackshare.io/gitential/gitential)
[xxxx](https://stackshare.io/xxxx/xxxx)
[Feedloop](https://stackshare.io/feedloop/feedloop)
[rakam](https://stackshare.io/rakam/rakam)
[appfollow](https://stackshare.io/appfollow/backend)
[Embrace](https://stackshare.io/embrace/embrace)
[STORETAIL](https://stackshare.io/storetail/storetail)
[WebGazer](https://stackshare.io/webgazer/webgazer)
[DataVisor](https://stackshare.io/datavisor/datavisor)
[Foxford](https://stackshare.io/foxford/foxford)
[extractBot](https://stackshare.io/extractbot/extractbot)
[Infostart](https://stackshare.io/infostart/infostart)
[metoda](https://stackshare.io/metoda-gmbh/product)
[GLAMI](https://stackshare.io/glami/glami)
[Gowit](https://stackshare.io/gowit/gowit)
[ODILO](https://stackshare.io/odilo/odilo)
[Push.World](https://stackshare.io/pushworld/push-world)

Also check the continuation of the list.

**Comment by tylerhannan** [comment]
A number of the companies in the list are not ClickHouse users (or we cannot demonstrate that they are)...rather this is half used as an actual "stack" list and also as an "interest" list.

As such, I will have to research each individually for other options. (especially as several of the companies no longer seem to exist).

I have requested API Access so that we can list more than the 45 in the UI to get a full list.

**Comment by tylerhannan** [comment]
API access was not granted. 

This is not an accurate list.
