### ISSUE TITLE
Improve screenshots on dbt page

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#83]
The screenshots on https://clickhouse.com/docs/en/integrations/dbt/dbt-connecting/ could be of higher quality, and the images are never scaled with the page. It is hard to look at them on wide screen

**Comment by DanRoscigno** [comment]
I edited the VS Code screenshot to remove all of the blank space and will submit a PR in a bit (once I look for other images that could be cropped / edited).  If you want I can look at this [extension](https://github.com/flexanalytics/plugin-image-zoom) that zooms on click.
