### ISSUE TITLE
Fix table for the Formats for Input and Output Data page

### ISSUE THREAD

**Issue by tom-clickhouse** [ClickHouse/clickhouse-docs#84]
The [table listing all our supported in and output formats](https://clickhouse.com/docs/en/interfaces/formats#formats) is broken since moving to Docusaurus.
<img width="955" alt="Screenshot 2022-05-10 at 14 15 24" src="https://user-images.githubusercontent.com/97666923/167637207-fa764b81-b7aa-49c8-a542-31a6a166ef6f.png">

**Comment by rfraposa** [comment]
Fixed with https://github.com/ClickHouse/ClickHouse/pull/37102
