### ISSUE TITLE
ANN Search Indexes Page Doc

### ISSUE THREAD

**Issue by dron-dronych** [ClickHouse/clickhouse-docs#846]
Broken link at https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/annindexes/ when trying to navigate to the [distance functions](https://clickhouse.com/docs/en/engines/sql-reference/functions/distance-functions) page from the Indexes Structure section.

**Comment by DanRoscigno** [comment]
Thanks @dron-dronych !
