### ISSUE TITLE
Can't click on links on integrations page

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-docs#857]
Links to resources on https://clickhouse.com/docs/en/integrations/ page aren't clickable due to a side-bar overlapping them
![2023-03-01_19-59-53](https://user-images.githubusercontent.com/3198181/222238529-30cdfb3a-6427-4065-b9dc-078e2dba5f72.png)

Browser: Chrome Version 110.0.5481.177 (Official Build) (arm64)

**Comment by DanRoscigno** [comment]
very strange, that is supposed to be off.  looking

**Comment by DanRoscigno** [comment]
looks like an extra <div> broke the class (we use a class written for the adopters page to remove the TOC and widen the table).  If that was the issue, then it will be fixed in 15 minutes.
