### ISSUE TITLE
Integration docs using wrong Rust logo

### ISSUE THREAD

**Issue by lew-gordon** [ClickHouse/clickhouse-docs#859]
In the [integration docs](https://clickhouse.com/docs/en/integrations/) I think the Rust logo being used is from the [video game](https://en.wikipedia.org/wiki/Rust_(video_game)) and not the [programming language](https://en.wikipedia.org/wiki/Rust_(programming_language)).

**Comment by DanRoscigno** [comment]
Thanks for catching that @lew-gordon , have a good one.
