### ISSUE TITLE
User guide for migrating from Amazon RedShift to ClickHouse Cloud

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#863]
Something to add to the docs...probably in the Knowledge Base

**Comment by johnnymatthews** [comment]
Is the [Migrating Data from Redshift to ClickHouse](https://clickhouse.com/docs/en/integrations/redshift#push-data-from-redshift-to-clickhouse) page not sufficient?

**Comment by rfraposa** [comment]
Yeah - that's probably sufficient.
