### ISSUE TITLE
User guide for migrating from Firebolt to ClickHouse Cloud

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#865]
Something to add to the docs...probably in the Knowledge Base

**Comment by johnnymatthews** [comment]
We have zero references to Firebolt in the docs right now. Since this is a fairly sizeable task, it'd be good to know how many ClickHouse users are asking for this content.

![image](https://github.com/ClickHouse/clickhouse-docs/assets/9611008/887c5cec-05fa-42e5-b4a7-c1ad4cc5cb1c)

**Comment by rfraposa** [comment]
I have a hunch that this was not well thought through and was hastily added to a prior Github issue. Closing for now.
