### ISSUE TITLE
Broken link but only intermittently

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/clickhouse-docs#892]
Something strange going on with this page, and I don't understand how.

In this Slack thread https://clickhouse-inc.slack.com/archives/C03A9B0H05T/p1678383970024679 - @kgoralski pointed out a broken link on this page:
https://clickhouse.com/docs/en/faq/operations/delete-old-data/

Specifically the link in the DROP PARTITIONS section https://clickhouse.com/docs/en/faq/operations/delete-old-data/#drop-partition 

This link:
More details on [manipulating partitions](https://clickhouse.com/docs/en/faq/sql-reference/statements/alter/partition/#alter_drop-partition).

I've tried clicking this multiple times. 3 of the times the link succeeded, but then once it failed. Seems like a web server or configuration or HA or caching problem maybe?

![image](https://user-images.githubusercontent.com/8918693/224117748-4db519d6-e166-4df2-b3f6-e74caad6c79c.png)

cc: @DanRoscigno

**Comment by thomoco** [comment]
This may require help from @tylerhannan please - seems like something maybe wrong with the caching or webserver configuration leading to intermittent 404s

**Comment by DanRoscigno** [comment]
no, bad file.

details are in the contrib guide https://github.com/ClickHouse/clickhouse-docs/blob/main/contrib-writing-guide.md#404s-

basically, missing `.md`, missing `/docs/en/` .  I think are six links in the doc, five were incorrectly written.  When I have time I will write a linter to check for this.
