### ISSUE TITLE
How to calculate the ratio of zero/default values in every column in a table?

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#906]
Alexey Milovidov:
 it will be nice to test ratio_of_defaults_for_sparse_serialization in ClickBench.
We can set it to 0.9 (or 0.99? what 

Anton: I think 0.95 is a good value to set by default in the future. But now we can use 0.9 for experiment to take effect on more columns because there are quite a lot of columns with ratio of defaults between 0.9 and 0.95: [https://play.clickhouse.com/play?user=play#c2VsZWN0ICogQVBQTFkgKHggLT4geCA9IGRlZmF1bHRWYWx1ZU9[…]m91bmQoeCwgMykpIEZST00gaGl0c18xMDBtX2NvbXBhdGlibGU=](https://play.clickhouse.com/play?user=play#c2VsZWN0ICogQVBQTFkgKHggLT4geCA9IGRlZmF1bHRWYWx1ZU9mQXJndW1lbnRUeXBlKHgpKSBBUFBMWSBhdmcgQVBQTFkgKHggLT4gcm91bmQoeCwgMykpIEZST00gaGl0c18xMDBtX2NvbXBhdGlibGU=)

```
select * APPLY (x -> x = defaultValueOfArgumentType(x)) APPLY avg APPLY (x -> round(x, 3)) FROM hits_100m_compatible
```

**Comment by gingerwizard** [comment]
Adding as KB now.

**Comment by gingerwizard** [comment]
@rfraposa you had already contributed this, thanks https://clickhouse.com/docs/knowledgebase/calculate_ratio_of_zero_sparse_serialization
