### ISSUE TITLE
Docs home not found

### ISSUE THREAD

**Issue by eliasyaoyc** [ClickHouse/clickhouse-docs#907]
On this page: https://clickhouse.com/docs/en/home/

<img width="418" alt="image" src="https://user-images.githubusercontent.com/46013886/225660648-d449739e-1ce4-49f1-8188-fa0ec4e857aa.png">
I get "Page Not Found" error.

**Comment by rfraposa** [comment]
Thanks - we know. We're having some technical difficulties deploying the new docs
