### ISSUE TITLE
Sitemap listing Vercel URL instead of clickhouse.com/docs

### ISSUE THREAD

**Issue by clickhouse-adrianfraguela** [ClickHouse/clickhouse-docs#911]
https://clickhouse.com/docs/sitemap.xml

This is being picked up by search console and it's throwing errors for all pages.

![Screenshot 2023-03-17 at 09 30 12](https://user-images.githubusercontent.com/119855513/225866318-e9c29ef6-7a89-4156-9e5c-c8fee7c1c43e.png)

![Screenshot 2023-03-17 at 09 30 42](https://user-images.githubusercontent.com/119855513/225866443-291af135-e323-4177-9a7a-13dd840a28b4.png)

**Comment by rfraposa** [comment]
@justindeguzman - do you know what this means, and do you have someone who can fix it?

**Comment by rfraposa** [comment]
Yes. The sitemap appears to be good now
