### ISSUE TITLE
How to check what code the server is running at this moment in time, without installing a debugger

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/clickhouse-docs#913]
ClickHouse has a built-in debugger and introspection capabilities.

You can get the stack traces of every server's thread at runtime by reading from the `system.stack_trace` table.

Enable it:
```
SET allow_introspection_functions = 1
```

Get the top 10 stack traces:
```
SELECT
   count(),
   arrayStringConcat(arrayMap(x -> concat(demangle(addressToSymbol(x)), '\n    ', addressToLine(x)), trace), '\n') AS sym
FROM system.stack_trace
GROUP BY trace
ORDER BY count() DESC
LIMIT 10
FORMAT Vertical
```

If you installed ClickHouse from a .deb/.rpm/.tgz you can also install the package with the debug info to see the line numbers from the source code:
```
sudo apt install clickhouse-common-static-dbg
```
If you've installed ClickHouse as a single-binary, it already contains the debug info.

The query result will show the locations in the ClickHouse source code where the threads are running or waiting. This information is meant for software engineers.

For more high-level information, see the `system.processes`, `system.query_log`, `system.metric_log`, `system.asynchronous_metric_log`, `system.trace_log`, `system.processor_profile_log` and other system tables.

**Comment by rfraposa** [comment]
Added here - thanks! https://github.com/ClickHouse/clickhouse-docs/pull/946
