### ISSUE TITLE
Additional docs nav feedback

### ISSUE THREAD

**Issue by justindeguzman** [ClickHouse/clickhouse-docs#930]
There's a few more outstanding docs nav feedback based on here (everything highlighted in yellow):
https://docs.google.com/document/d/1r9aXvbRkJwk2cWiYLQnWDZfEJWoHeovh4RIE4gmADuY/edit

Not urgent and can be completed whenever, just think these improvements would be good!

**Comment by rfraposa** [comment]
Thanks Justin....I think I got all the changes incorporated now.

**Comment by justindeguzman** [comment]
Thanks Rich, lgtm!
