### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by nellicus** [ClickHouse/clickhouse-docs#941]
in https://clickhouse.com/docs/knowledgebase/file-export

this link https://clickhouse.com/docs/en/engines/table-engines/special/file.md 

![Screenshot 2023-03-24 at 13 30 08](https://user-images.githubusercontent.com/8770097/227521746-2c4be25b-4db7-44dc-ae78-0bb536ad4f8e.png)

yields 404

**Comment by rfraposa** [comment]
Thanks! Fixed here: https://github.com/ClickHouse/clickhouse-docs/pull/945
