### ISSUE TITLE
Add UNDROP TABLE to docs

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#969]
You have 8 minutes to UNDROP a table that was dropped. Include `system.dropped_tables`

**Comment by DanRoscigno** [comment]
notes 

set allow_experimental_undrop_table_query = 1;

system.dropped_tables

create table undropMe
id UInt8                                                   
Engine=MergeTree() order by id;

database_atomic_wait_for_drop_and_detach_synchronously

add note to https://clickhouse.com/docs/en/sql-reference/statements/drop#drop-table linking to undrop
