### ISSUE TITLE
Add allow_experimental_parallel_reading_from_replicas 

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-docs#971]
You need to enable this flag in order to use `max_parallel_replicas`

**Comment by DanRoscigno** [comment]
@rfraposa , Do you have a reference for this?

**Comment by rfraposa** [comment]
Just an example: https://presentations.clickhouse.com/release_23.3/#19

and the source code: https://github.com/ClickHouse/ClickHouse/blob/90a1a75424caaa4704d956d85423c53104f8a079/src/Core/Settings.h#L153

**Comment by DanRoscigno** [comment]
I found those, but not any reference that says the experimental setting is required.  This works just fine:
```
SET max_parallel_replicas = 10
SELECT count() FROM tablename
```

I will listen to the recording to see if there is any info in there.

**Comment by rfraposa** [comment]
Good point - maybe you don't need the setting! I just noticed it during the webinar and realized it was nowhere in the docs. 

Maybe @alexey-milovidov can tell us?

**Comment by alexey-milovidov** [comment]
The `max_parallel_replicas` without the new "parallel reading from replicas" option activates the usage of the SAMPLE key for parallel replicas. See https://clickhouse.com/docs/en/operations/settings/settings#parallel-processing-using-sample-key
